import { Sigma } from 'lucide-react-native';
import type { CourseModule } from '../types/course';

export const mathAICourse: CourseModule = {
  id: 'math-ai',
  title: 'Math for AI',
  subtitle: 'Statistics, probability, Bayes, distributions',
  color: '#D4A843',
  accent: '#FFF5DC',
  Icon: Sigma,
  history: {
    founder: 'Centuries of mathematicians',
    released: 'Ancient–Modern',
    summary:
      'Statistics and probability are the mathematical spine of AI. From Bayes\' theorem (1763) to modern gradient descent, every ML algorithm rests on these ideas.',
  },
  concepts: [
    'Mean, median, mode — measures of center',
    'Variance and standard deviation — spread',
    'Probability rules: P(A and B), P(A or B)',
    'Conditional probability and Bayes\' theorem',
    'Correlation vs causation',
    'Normal, uniform, and binomial distributions',
    'Expected value and law of large numbers',
    'Sampling and the Central Limit Theorem',
  ],
  lessons: [
    {
      id: 'math-central',
      title: 'Mean, Median, and Variance',
      duration: '20 min',
      objective: 'Summarize datasets with center and spread statistics.',
      blocks: [
        { type: 'heading', text: 'Measures of Center' },
        {
          type: 'paragraph',
          text: 'Before any model can learn, you must understand your data. We typically start by looking at where the data is centered (Mean and Median). The mean is highly sensitive to outliers, whereas the median is robust.',
        },
        {
          type: 'analogy',
          text: 'Imagine 9 people in a room earning $50,000, and Elon Musk walks in. The "Mean" wealth jumps to billions, misleadingly suggesting everyone is rich. The "Median" wealth stays at $50,000, accurately reflecting the typical person.',
        },
        {
          type: 'formula',
          expression: '\\text{Mean } (\\mu) = \\frac{1}{n} \\sum_{i=1}^n x_i',
          note: 'Sum all values and divide by the count (n).',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Measures of Spread' },
        {
          type: 'paragraph',
          text: 'Center isn\'t enough. We need to know how wildly the data fluctuates around that center. Variance calculates the average squared distance from the mean, and Standard Deviation simply takes the square root to return to the original units.',
        },
        {
          type: 'formula',
          expression: '\\text{Variance } (\\sigma^2) = \\frac{1}{n} \\sum_{i=1}^n (x_i - \\mu)^2',
          note: 'Squaring penalizes large deviations heavily.',
        },
        {
          type: 'formula',
          expression: '\\text{Std Dev } (\\sigma) = \\sqrt{\\sigma^2}',
          note: 'Brings the spread back into readable units.',
        },
        {
          type: 'playground',
          code: 'import numpy as np\ndata = np.array([4, 8, 6, 5, 3, 7, 9])\nprint(f"Mean: {data.mean():.2f}")\nprint(f"Std: {data.std():.2f}")\nprint(f"Median: {np.median(data):.2f}")',
          expectedOutput: 'Mean: 6.00\nStd: 1.90\nMedian: 6.00',
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'Scaling Features',
          body: 'If variance is wildly different across features (e.g. predicting price from Age vs. Mileage), machine learning models struggle. Always standardize data so standard deviation equals 1.',
        },
      ],
    },
    {
      id: 'math-probability',
      title: 'Probability Basics',
      duration: '22 min',
      objective: 'Reason about uncertain events using probability rules.',
      blocks: [
        { type: 'heading', text: 'Modeling Uncertainty' },
        {
          type: 'paragraph',
          text: 'Artificial Intelligence does not deal in absolutes; it deals in probabilities. Classifiers output a percentage likelihood, e.g., "99.2% chance this image is a dog".',
        },
        {
          type: 'formula',
          expression: 'P(A) = \\frac{\\text{favorable}}{\\text{total}}',
          note: 'Probability is strictly bounded between 0 and 1.',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Combining Probabilities' },
        {
          type: 'table',
          headers: ['Rule Name', 'Condition', 'Formula'],
          rows: [
            ['Addition (OR)', 'Mutually Exclusive', 'P(A) + P(B)'],
            ['Addition (OR)', 'Overlapping Events', 'P(A) + P(B) - P(A and B)'],
            ['Multiplication (AND)', 'Independent Events', 'P(A) × P(B)'],
          ],
        },
        {
          type: 'playground',
          code: 'p_rain = 0.3\np_umbrella = 0.6\np_both = 0.25\np_either = p_rain + p_umbrella - p_both\nprint(f"P(rain or umbrella) = {p_either}")',
          expectedOutput: 'P(rain or umbrella) = 0.65',
        },
        {
          type: 'callout',
          variant: 'warning',
          title: 'Dependent Events',
          body: 'If events are NOT independent, you cannot simply multiply their probabilities. You must use Conditional Probability: P(A and B) = P(A) × P(B|A).',
        },
      ],
    },
    {
      id: 'math-bayes',
      title: 'Bayes\' Theorem',
      duration: '25 min',
      objective: 'Update beliefs with evidence using Bayes\' rule.',
      blocks: [
        { type: 'heading', text: 'Updating Beliefs' },
        {
          type: 'paragraph',
          text: 'Bayes\' theorem is the mathematical framework for changing your mind when you see new evidence. It is the engine behind spam filters and Bayesian neural networks.',
        },
        {
          type: 'formula',
          expression: 'P(A|B) = \\frac{P(B|A) \\cdot P(A)}{P(B)}',
          note: 'Posterior = (Likelihood × Prior) / Evidence',
        },
        {
          type: 'stepByStep',
          title: 'Components of Bayes Theorem',
          steps: [
            { title: 'Prior P(A)', description: 'Your initial belief before seeing any new data.' },
            { title: 'Likelihood P(B|A)', description: 'How probable the new evidence is, assuming your belief is true.' },
            { title: 'Evidence P(B)', description: 'The total probability of seeing this evidence under all circumstances.' },
            { title: 'Posterior P(A|B)', description: 'Your updated, refined belief.' },
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'The Rare Disease Paradox' },
        {
          type: 'paragraph',
          text: 'A disease affects 1% of the population. A test is 95% accurate. If you test positive, what is the actual probability you are sick?',
        },
        {
          type: 'playground',
          code: 'p_disease = 0.01\np_pos_given_sick = 0.95\np_pos_given_healthy = 0.05\n\n# Total probability of testing positive\np_pos = (p_pos_given_sick * p_disease) + (p_pos_given_healthy * (1 - p_disease))\n\n# Bayes theorem\np_sick_given_pos = (p_pos_given_sick * p_disease) / p_pos\nprint(f"Chance you are sick: {p_sick_given_pos:.1%}")',
          expectedOutput: 'Chance you are sick: 16.1%',
        },
        {
          type: 'callout',
          variant: 'info',
          title: 'The Base Rate Fallacy',
          body: 'Even with a 95% accurate test, you only have a 16.1% chance of being sick! Because the disease is so rare, false positives vastly outnumber true positives.',
        },
      ],
    },
    {
      id: 'math-correlation',
      title: 'Correlation and Covariance',
      duration: '20 min',
      objective: 'Measure relationships between variables.',
      blocks: [
        { type: 'heading', text: 'Measuring Relationships' },
        {
          type: 'paragraph',
          text: 'Correlation tells you if two variables move together. It ranges from -1 (perfectly opposite) to +1 (perfectly together). 0 means absolutely no linear relationship.',
        },
        {
          type: 'formula',
          expression: 'r = \\frac{\\sum(x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum(x_i - \\bar{x})^2 \\cdot \\sum(y_i - \\bar{y})^2}}',
          note: 'Pearson correlation coefficient formula.',
        },
        {
          type: 'playground',
          code: 'import numpy as np\nhours = np.array([1, 2, 3, 4, 5])\nscores = np.array([50, 60, 65, 80, 90])\ncorrelation = np.corrcoef(hours, scores)[0, 1]\nprint(f"Correlation: {correlation:.3f}")',
          expectedOutput: 'Correlation: 0.986',
        },
        {
          type: 'callout',
          variant: 'warning',
          title: 'Correlation is NOT Causation',
          body: 'Ice cream sales are heavily correlated with shark attacks. Why? Because both happen in the summer. A hidden third variable (confounder) can easily trick algorithms into learning false causation.',
        },
      ],
    },
    {
      id: 'math-distributions',
      title: 'Distributions',
      duration: '22 min',
      objective: 'Recognize and use normal, uniform, and binomial distributions.',
      blocks: [
        { type: 'heading', text: 'The Shape of Data' },
        {
          type: 'paragraph',
          text: 'Distributions describe how data spreads out. The Normal Distribution (Bell Curve) is the most important concept in statistics because nature naturally clusters around it.',
        },
        {
          type: 'table',
          headers: ['Distribution', 'Shape', 'Use Case in AI'],
          rows: [
            ['Normal (Gaussian)', 'Bell Curve', 'Residual errors, height, test scores'],
            ['Uniform', 'Flat Rectangle', 'Random weight initialization'],
            ['Binomial', 'Discrete Bars', 'Coin flips, CTR (Click-Through Rate)'],
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'The 68-95-99.7 Rule' },
        {
          type: 'paragraph',
          text: 'For any perfectly normal distribution:',
        },
        {
          type: 'bullets',
          items: [
            '68% of data falls within 1 Standard Deviation (σ).',
            '95% of data falls within 2 Standard Deviations.',
            '99.7% of data falls within 3 Standard Deviations.',
          ],
        },
        {
          type: 'playground',
          code: 'import numpy as np\nnp.random.seed(42)\nsamples = np.random.normal(loc=100, scale=15, size=1000)\n\n# Count how many fall within 1 standard deviation\nwithin_1_std = np.sum(np.abs(samples - samples.mean()) < samples.std()) / len(samples)\nprint(f"Percentage within 1 std: {within_1_std:.1%}")',
          expectedOutput: 'Percentage within 1 std: 68.4%',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'math-q1',
      prompt: 'What does standard deviation measure?',
      options: ['Spread of data from the mean', 'The most common value', 'The middle value', 'The range of data'],
      answerIndex: 0,
      explanation: 'Standard deviation quantifies how much values deviate from the mean.',
    },
    {
      id: 'math-q2',
      prompt: 'What is P(not A) if P(A) = 0.3?',
      options: ['0.7', '0.3', '1.3', '0.0'],
      answerIndex: 0,
      explanation: 'P(not A) = 1 - P(A) = 1 - 0.3 = 0.7.',
    },
    {
      id: 'math-q3',
      prompt: 'In Bayes\' theorem, what is the "prior"?',
      options: ['Your belief before seeing evidence', 'The probability of the evidence', 'The test accuracy', 'The sample size'],
      answerIndex: 0,
      explanation: 'The prior P(A) represents your initial belief before new data.',
    },
    {
      id: 'math-q4',
      prompt: 'A correlation of -0.9 means:',
      options: ['Strong negative linear relationship', 'No relationship', 'Strong positive relationship', 'Causation is proven'],
      answerIndex: 0,
      explanation: 'Values near -1 indicate a strong inverse linear relationship.',
    },
    {
      id: 'math-q5',
      prompt: 'What percentage of data falls within 2 standard deviations of the mean in a normal distribution?',
      options: ['95%', '68%', '99.7%', '50%'],
      answerIndex: 0,
      explanation: 'The 68-95-99.7 rule: ~95% falls within 2σ of the mean.',
    },
    {
      id: 'math-q6',
      prompt: 'Why is median preferred over mean for skewed data?',
      options: ['It is not affected by outliers', 'It is easier to compute', 'It is always larger', 'It works only with integers'],
      answerIndex: 0,
      explanation: 'Outliers pull the mean but don\'t affect the median.',
    },
    {
      id: 'math-q7',
      prompt: 'What does "correlation does not imply causation" mean?',
      options: ['Two variables can move together without one causing the other', 'Correlation is always zero', 'Causation cannot be measured', 'You need more data'],
      answerIndex: 0,
      explanation: 'A hidden third variable (confound) can make unrelated variables appear correlated.',
    },
    {
      id: 'math-q8',
      prompt: 'What distribution models the number of heads in 10 coin flips?',
      options: ['Binomial', 'Normal', 'Uniform', 'Exponential'],
      answerIndex: 0,
      explanation: 'Binomial distribution models the count of successes in fixed independent trials.',
    },
    {
      id: 'math-q9',
      prompt: 'What does the Central Limit Theorem state?',
      options: ['Sample means approach a normal distribution', 'All data is normal', 'Larger samples are always better', 'Mean equals median'],
      answerIndex: 0,
      explanation: 'Regardless of the population shape, sample means tend toward normal as sample size grows.',
    },
    {
      id: 'math-q10',
      prompt: 'If variance is 25, what is the standard deviation?',
      options: ['5', '25', '625', '12.5'],
      answerIndex: 0,
      explanation: 'Standard deviation = √variance = √25 = 5.',
    },
  ],
  practice: [
    {
      id: 'math-p1',
      title: 'Compute Mean and Std',
      prompt: 'Calculate mean and standard deviation of a dataset.',
      starterCode: 'import numpy as np\ndata = np.array([4, 8, 6, 5, 3, 7, 9])\nprint(f"Mean: {data.mean():.2f}")\nprint(f"Std: {data.std():.2f}")',
      expectedOutput: 'Mean: 6.00\nStd: 1.90',
      hint: 'Use .mean() and .std() on a NumPy array.',
    },
    {
      id: 'math-p2',
      title: 'Probability Union',
      prompt: 'Calculate P(A or B) given P(A), P(B), and P(A and B).',
      starterCode: 'p_a = 0.4\np_b = 0.5\np_both = 0.2\nprint(f"P(A or B) = {p_a + p_b - p_both}")',
      expectedOutput: 'P(A or B) = 0.7',
      hint: 'P(A or B) = P(A) + P(B) - P(A and B).',
    },
    {
      id: 'math-p3',
      title: 'Bayes Calculator',
      prompt: 'Compute the posterior probability using Bayes\' theorem.',
      starterCode: 'p_disease = 0.01\np_pos_disease = 0.95\np_pos_healthy = 0.05\np_pos = p_pos_disease * p_disease + p_pos_healthy * (1 - p_disease)\nposterior = (p_pos_disease * p_disease) / p_pos\nprint(f"Posterior: {posterior:.3f}")',
      expectedOutput: 'Posterior: 0.161',
      hint: 'Apply Bayes: P(D|+) = P(+|D)*P(D) / P(+).',
    },
    {
      id: 'math-p4',
      title: 'Correlation',
      prompt: 'Compute the Pearson correlation between hours and scores.',
      starterCode: 'import numpy as np\nhours = np.array([1, 2, 3, 4, 5])\nscores = np.array([50, 60, 65, 80, 90])\nr = np.corrcoef(hours, scores)[0, 1]\nprint(f"r = {r:.3f}")',
      expectedOutput: 'r = 0.986',
      hint: 'np.corrcoef returns a matrix; [0,1] gives the correlation.',
    },
    {
      id: 'math-p5',
      title: 'Normal Samples',
      prompt: 'Generate normal samples and check what fraction is within 1 std.',
      starterCode: 'import numpy as np\nnp.random.seed(0)\ndata = np.random.normal(50, 10, 1000)\nwithin = np.sum(np.abs(data - data.mean()) < data.std()) / len(data)\nprint(f"Within 1 std: {within:.1%}")',
      expectedOutput: 'Within 1 std: 68.8%',
      hint: 'About 68% of normal data falls within 1 standard deviation.',
    },
    {
      id: 'math-p6',
      title: 'Z-Score',
      prompt: 'Standardize a value: compute its z-score.',
      starterCode: 'mean = 100\nstd = 15\nvalue = 130\nz = (value - mean) / std\nprint(f"Z-score: {z:.2f}")',
      expectedOutput: 'Z-score: 2.00',
      hint: 'z = (x - mean) / std. A z of 2 means 2 std above the mean.',
    },
  ],
};
