import { Workflow } from 'lucide-react-native';
import type { CourseModule } from '../types/course';

export const pythonAdvancedCourse: CourseModule = {
  id: 'python-advanced',
  title: 'Python Advanced',
  subtitle: 'OOP, decorators, generators, error handling',
  color: '#6B4C9A',
  accent: '#EDE5F7',
  Icon: Workflow,
  history: {
    founder: 'Guido van Rossum',
    released: '1991',
    summary:
      'Python\'s advanced features — classes, generators, decorators — let you build large, maintainable AI projects. Most ML frameworks are built on these patterns.',
  },
  concepts: [
    'Classes, objects, and __init__',
    'Inheritance and method overriding',
    'Decorators as function wrappers',
    'Generators and yield for lazy iteration',
    'try / except / finally error handling',
    'Context managers (with statement)',
    'Modules and packages',
    'Type hints for documentation',
  ],
  lessons: [
    {
      id: 'pya-oop',
      title: 'Classes and OOP',
      duration: '22 min',
      objective: 'Model real-world entities with classes, attributes, and methods.',
      blocks: [
        { type: 'heading', text: 'Object-Oriented Programming (OOP)' },
        {
          type: 'paragraph',
          text: 'As your Python projects grow from small scripts to massive ML frameworks, you need a way to organize related variables and functions. A `class` serves as a blueprint for creating highly organized, reusable objects.',
        },
        {
          type: 'analogy',
          text: 'Think of a class as the architectural blueprint of a house. The blueprint defines where the rooms and doors go. An object (instance) is the actual physical house built from that blueprint. You can build many identical houses (objects) from one single blueprint (class).',
        },
        {
          type: 'stepByStep',
          title: 'Creating and Using a Class',
          steps: [
            { title: 'Define the Class', description: 'Use the `class` keyword followed by a capitalized name.' },
            { title: 'Write the Constructor', description: 'The `__init__` method runs automatically to set up the object\'s initial state.' },
            { title: 'Create Instances', description: 'Call the class name like a function to create a unique, independent object in memory.' },
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'Building a Neural Class' },
        {
          type: 'playground',
          code: 'class Neuron:\n    def __init__(self, weight, bias):\n        # self refers to the specific instance\n        self.weight = weight\n        self.bias = bias\n\n    def forward(self, x):\n        return self.weight * x + self.bias\n\n# Creating two distinct neurons\nn1 = Neuron(0.5, 2)\nn2 = Neuron(1.5, -1)\n\nprint(f"Neuron 1 output: {n1.forward(10)}")\nprint(f"Neuron 2 output: {n2.forward(10)}")',
          expectedOutput: 'Neuron 1 output: 7.0\nNeuron 2 output: 14.0',
        },
        {
          type: 'callout',
          variant: 'remember',
          title: 'The Magic of `self`',
          body: 'When defining methods inside a class, the first parameter must always be `self`. Python automatically passes the specific object instance into `self` so the method knows whose data it is modifying.',
        },
      ],
    },
    {
      id: 'pya-decorators',
      title: 'Decorators and Generators',
      duration: '24 min',
      objective: 'Wrap functions with decorators and produce values lazily with generators.',
      blocks: [
        { type: 'heading', text: 'Decorators: Function Wrappers' },
        {
          type: 'paragraph',
          text: 'A decorator allows you to modify or enhance the behavior of a function without permanently changing its source code. It is essentially a function that takes another function as an argument and returns an updated function.',
        },
        {
          type: 'analogy',
          text: 'Imagine a decorator as a gift wrapping service. You hand them your plain box (the original function), and they hand it back covered in beautiful paper with a bow (the wrapped function), but the contents inside remain exactly the same.',
        },
        {
          type: 'playground',
          code: 'def timer(func):\n    def wrapper(*args):\n        print(f"Starting {func.__name__}...")\n        result = func(*args)\n        print("Finished!")\n        return result\n    return wrapper\n\n@timer\ndef add(a, b):\n    return a + b\n\nprint(f"Result: {add(3, 4)}")',
          expectedOutput: 'Starting add...\nFinished!\nResult: 7',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Generators: Lazy Sequences' },
        {
          type: 'paragraph',
          text: 'When training AI models on billions of images, you cannot load the entire dataset into memory at once. Generators solve this by using the `yield` keyword to produce one item at a time, pausing execution until the next item is requested.',
        },
        {
          type: 'table',
          headers: ['Concept', 'Keyword', 'Memory Usage', 'Best For'],
          rows: [
            ['Standard Function', 'return', 'High (Returns all data)', 'Small lists'],
            ['Generator', 'yield', 'Extremely Low', 'Massive datasets (streaming)'],
          ],
        },
        {
          type: 'playground',
          code: 'def fibonacci(limit):\n    a, b = 0, 1\n    for _ in range(limit):\n        yield a\n        a, b = b, a + b\n\n# The generator yields one value per iteration\nfor num in fibonacci(5):\n    print(num)',
          expectedOutput: '0\n1\n1\n2\n3',
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'Yield Pauses State',
          body: 'Unlike `return` which instantly terminates a function, `yield` merely pauses it. When the generator is called again, it resumes executing immediately after the `yield` statement with all variables completely intact.',
        },
      ],
    },
    {
      id: 'pya-errors',
      title: 'Error Handling',
      duration: '18 min',
      objective: 'Write robust code that handles failures gracefully.',
      blocks: [
        { type: 'heading', text: 'Guarding Against Crashes' },
        {
          type: 'paragraph',
          text: 'Production software interacts with unpredictable environments (missing network connections, corrupt files, unexpected user inputs). Instead of allowing the program to crash, Python allows you to "catch" these errors gracefully using `try / except` blocks.',
        },
        {
          type: 'diagram',
          title: 'Try/Except Flow',
          boxes: [
            { id: 'try', x: 70, y: 10, width: 90, height: 40, label: 'Try Block', color: '#2B6CB0' },
            { id: 'pass', x: 20, y: 80, width: 70, height: 40, label: 'Success', color: '#1D7A57' },
            { id: 'fail', x: 140, y: 80, width: 70, height: 40, label: 'Exception', color: '#E44D6E' },
          ],
          arrows: [
            { from: 'try', to: 'pass', label: 'Works' },
            { from: 'try', to: 'fail', label: 'Crashes' },
          ],
          height: 140,
        },
        {
          type: 'playground',
          code: 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero!"\n    finally:\n        print("Cleanup: Operation attempted.")\n\nprint(safe_divide(10, 2))\nprint(safe_divide(10, 0))',
          expectedOutput: 'Cleanup: Operation attempted.\n5.0\nCleanup: Operation attempted.\nCannot divide by zero!',
        },
        {
          type: 'callout',
          variant: 'warning',
          title: 'Avoid Bare Exceptions',
          body: 'Never use a bare `except:` without specifying the error type. Doing so will catch system exit commands and keyboard interrupts, making your program impossible to stop. Always specify the error (e.g. `except ValueError:`).',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'pya-q1',
      prompt: 'What does __init__ do in a Python class?',
      options: ['Initializes a new object', 'Deletes an object', 'Imports a module', 'Defines a global variable'],
      answerIndex: 0,
      explanation: '__init__ is the constructor — it runs when you create an instance.',
    },
    {
      id: 'pya-q2',
      prompt: 'What does the self parameter refer to?',
      options: ['The current object instance', 'The class itself', 'The parent class', 'A global variable'],
      answerIndex: 0,
      explanation: 'self is a reference to the specific object calling the method.',
    },
    {
      id: 'pya-q3',
      prompt: 'What does yield do in a function?',
      options: ['Pauses and produces a value', 'Ends the function', 'Raises an error', 'Imports a module'],
      answerIndex: 0,
      explanation: 'yield produces a value and suspends the function state until next() is called.',
    },
    {
      id: 'pya-q4',
      prompt: 'What is a decorator?',
      options: ['A function that wraps another function', 'A CSS class', 'A type hint', 'A loop construct'],
      answerIndex: 0,
      explanation: 'Decorators take a function, add behavior, and return a new function.',
    },
    {
      id: 'pya-q5',
      prompt: 'Which block always runs, even if an error occurs?',
      options: ['finally', 'except', 'else', 'try'],
      answerIndex: 0,
      explanation: 'finally runs after try/except regardless of whether an error occurred.',
    },
    {
      id: 'pya-q6',
      prompt: 'What does class Dog(Animal) mean?',
      options: ['Dog inherits from Animal', 'Dog is inside Animal', 'Dog deletes Animal', 'Dog is a module'],
      answerIndex: 0,
      explanation: 'Parentheses after the class name indicate inheritance from the parent class.',
    },
    {
      id: 'pya-q7',
      prompt: 'What makes generators memory-efficient?',
      options: ['They produce values one at a time', 'They compress data', 'They run on GPU', 'They use less disk space'],
      answerIndex: 0,
      explanation: 'Generators yield items lazily instead of storing the entire sequence in memory.',
    },
    {
      id: 'pya-q8',
      prompt: 'How do you catch a specific error type?',
      options: ['except ValueError:', 'catch ValueError:', 'handle ValueError:', 'error ValueError:'],
      answerIndex: 0,
      explanation: 'Python uses "except ErrorType:" to catch specific exception types.',
    },
    {
      id: 'pya-q9',
      prompt: 'What is the purpose of __name__ == "__main__"?',
      options: ['Run code only when the file is executed directly', 'Import all modules', 'Define the main class', 'Set the file name'],
      answerIndex: 0,
      explanation: 'This guard prevents code from running when the file is imported as a module.',
    },
    {
      id: 'pya-q10',
      prompt: 'What does pip install do?',
      options: ['Installs a third-party package', 'Creates a new file', 'Compiles Python to C', 'Starts a web server'],
      answerIndex: 0,
      explanation: 'pip is Python\'s package installer for downloading libraries from PyPI.',
    },
  ],
  practice: [
    {
      id: 'pya-p1',
      title: 'Simple Class',
      prompt: 'Create a Neuron class with forward(x) that computes weight*x + bias.',
      starterCode: 'class Neuron:\n    def __init__(self, weight, bias):\n        self.weight = weight\n        self.bias = bias\n    def forward(self, x):\n        return self.weight * x + self.bias\n\nn = Neuron(0.5, 2)\nprint(n.forward(10))',
      expectedOutput: '7.0',
      hint: 'forward returns self.weight * x + self.bias.',
    },
    {
      id: 'pya-p2',
      title: 'Generator Range',
      prompt: 'Write a generator that yields squares from 0 to n-1.',
      starterCode: 'def squares_gen(n):\n    for i in range(n):\n        yield i ** 2\n\nprint(list(squares_gen(5)))',
      expectedOutput: '[0, 1, 4, 9, 16]',
      hint: 'Use yield inside a for loop.',
    },
    {
      id: 'pya-p3',
      title: 'Safe Division',
      prompt: 'Write a function that handles ZeroDivisionError.',
      starterCode: 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Error"\n\nprint(safe_divide(10, 0))',
      expectedOutput: 'Error',
      hint: 'Wrap the division in try/except ZeroDivisionError.',
    },
    {
      id: 'pya-p4',
      title: 'Inheritance',
      prompt: 'Create Animal and Dog classes where Dog inherits speak().',
      starterCode: 'class Animal:\n    def speak(self):\n        return "..."\n\nclass Dog(Animal):\n    def speak(self):\n        return "Woof!"\n\nprint(Dog().speak())',
      expectedOutput: 'Woof!',
      hint: 'Override the speak method in the Dog class.',
    },
    {
      id: 'pya-p5',
      title: 'Math Module',
      prompt: 'Use the math module to compute the square root of 144.',
      starterCode: 'import math\nprint(math.sqrt(144))',
      expectedOutput: '12.0',
      hint: 'math.sqrt() returns the square root as a float.',
    },
  ],
};
