import { Code2 } from 'lucide-react-native';
import type { CourseModule } from '../types/course';

export const pythonBasicsCourse: CourseModule = {
  id: 'python-basics',
  title: 'Python Basics',
  subtitle: 'Variables, control flow, functions, data structures',
  color: '#3776AB',
  accent: '#E0EEFF',
  Icon: Code2,
  history: {
    founder: 'Guido van Rossum',
    released: '1991',
    summary:
      'Python was designed for readability and simplicity. It became the dominant language in AI and data science because of its clean syntax and rich ecosystem.',
  },
  concepts: [
    'Variables and data types (int, float, str, bool)',
    'Operators and expressions',
    'if / elif / else control flow',
    'for and while loops',
    'Functions with parameters and return values',
    'Lists, tuples, dictionaries, and sets',
    'String formatting and methods',
    'File reading and writing',
    'List comprehensions',
    'Importing modules',
  ],
  lessons: [
    {
      id: 'py-variables',
      title: 'Variables and Data Types',
      duration: '15 min',
      objective: 'Understand how Python stores data in variables with types.',
      blocks: [
        { type: 'heading', text: 'What is a Variable?' },
        {
          type: 'paragraph',
          text: 'A variable is a name that refers to a value stored in your computer\'s memory. In Python, you create a variable simply by assigning a value to a name using the = sign. Unlike many other languages, you don\'t need to declare the type — Python figures it out automatically.',
        },
        {
          type: 'analogy',
          text: 'A variable is like a labeled box in a warehouse. The label (variable name) tells you what\'s inside, and you can swap the contents anytime. The box labeled "age" might hold 25 today and 26 next year.',
        },
        {
          type: 'image',
          title: 'Variables store values in labeled memory boxes',
          imageType: 'variable-boxes',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Creating Variables' },
        {
          type: 'paragraph',
          text: 'Python is dynamically typed — you don\'t declare types, you just assign. The interpreter figures out the type from the value you give it.',
        },
        {
          type: 'code',
          code: 'name = "Ada"\\nage = 30\\npi = 3.14159\\nis_student = True\\nprint(type(name), type(age), type(pi))',
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'Dynamic Typing',
          body: 'You can reassign a variable to a completely different type: x = 5 then x = "hello" is perfectly valid in Python. This flexibility is powerful but requires careful attention.',
        },
        {
          type: 'table',
          headers: ['Type', 'Example', 'Description'],
          rows: [
            ['int', '42', 'Whole numbers (no decimals)'],
            ['float', '3.14', 'Decimal numbers'],
            ['str', '"hello"', 'Text enclosed in quotes'],
            ['bool', 'True / False', 'Logical values'],
            ['NoneType', 'None', 'Absence of a value'],
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'Try It Yourself' },
        {
          type: 'playground',
          code: 'x = 42\\ny = 3.14\\nz = "hello"\\nprint(type(x))\\nprint(type(y))\\nprint(type(z))',
          expectedOutput: "<class 'int'>\n<class 'float'>\n<class 'str'>",
        },
        {
          type: 'stepByStep',
          title: 'How Python Assigns a Variable',
          steps: [
            { title: 'You write x = 42', description: 'Python sees the assignment operator = and prepares to store a value.' },
            { title: 'Python creates the value 42', description: 'The integer 42 is created in memory as an int object.' },
            { title: 'The name x points to it', description: 'The variable name "x" becomes a reference (label) pointing to that 42 in memory.' },
            { title: 'type() checks the label', description: 'Calling type(x) looks at what x points to and tells you it\'s an int.' },
          ],
        },
        {
          type: 'formula',
          expression: 'int → whole numbers | float → decimals | str → text | bool → True/False',
          note: 'Python converts between types automatically in many cases (int + float = float).',
        },
        {
          type: 'callout',
          variant: 'remember',
          title: 'Naming Rules',
          body: 'Variable names are case-sensitive (age ≠ Age). Use snake_case: my_score, not myScore. Names must start with a letter or underscore, never a number.',
        },
        {
          type: 'bullets',
          items: [
            'Variable names are case-sensitive: age ≠ Age.',
            'Use snake_case for variable names: my_score, not myScore.',
            'None represents the absence of a value.',
            'Use type() to check any variable\'s type at runtime.',
          ],
        },
      ],
    },
    {
      id: 'py-control-flow',
      title: 'Control Flow',
      duration: '18 min',
      objective: 'Make decisions and repeat actions with if/else and loops.',
      blocks: [
        { type: 'heading', text: 'Making Decisions' },
        {
          type: 'paragraph',
          text: 'Control flow determines which code runs and how many times. Python uses indentation (not braces) to define blocks. This makes your code visually represent its logical structure.',
        },
        {
          type: 'analogy',
          text: 'Control flow is like a road with forks. At each fork (if statement), you check a sign (condition) and take the matching path. Loops are roundabouts — you keep going around until a condition lets you exit.',
        },
        {
          type: 'image',
          title: 'If/Else creates two execution paths based on a condition',
          imageType: 'if-else-branch',
        },
        {
          type: 'code',
          code: 'score = 85\\nif score >= 90:\\n    grade = "A"\\nelif score >= 80:\\n    grade = "B"\\nelse:\\n    grade = "C"\\nprint(grade)',
        },
        {
          type: 'callout',
          variant: 'warning',
          title: 'Indentation Matters!',
          body: 'Python uses 4 spaces for indentation (not tabs). Mixing spaces and tabs will cause an IndentationError. Most editors handle this automatically, but be aware!',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Loops — Repeating Actions' },
        {
          type: 'image',
          title: 'A loop repeats the body while the condition is true',
          imageType: 'loop-flow',
        },
        {
          type: 'playground',
          code: 'total = 0\\nfor i in range(1, 6):\\n    total += i\\nprint(total)',
          expectedOutput: '15',
        },
        {
          type: 'stepByStep',
          title: 'How a For Loop Executes',
          steps: [
            { title: 'range(1, 6) creates [1, 2, 3, 4, 5]', description: 'The range function generates numbers from start (1) up to but NOT including stop (6).' },
            { title: 'i = 1, total = 0 + 1 = 1', description: 'First iteration: i takes the value 1, total becomes 1.' },
            { title: 'i = 2, total = 1 + 2 = 3', description: 'Second iteration: i becomes 2, total grows to 3.' },
            { title: '...continues until i = 5', description: 'total = 1+2+3+4+5 = 15. The loop ends when all values are consumed.' },
          ],
        },
        {
          type: 'code',
          code: 'fruits = ["apple", "banana", "cherry"]\\nfor fruit in fruits:\\n    print(fruit.upper())',
        },
        {
          type: 'table',
          headers: ['Keyword', 'Purpose', 'Example'],
          rows: [
            ['if', 'Check a condition', 'if x > 5:'],
            ['elif', 'Additional condition', 'elif x > 3:'],
            ['else', 'Fallback branch', 'else:'],
            ['for', 'Loop over items', 'for i in range(5):'],
            ['while', 'Loop while true', 'while x > 0:'],
            ['break', 'Exit loop early', 'break'],
            ['continue', 'Skip iteration', 'continue'],
          ],
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'When to use for vs while',
          body: 'Use "for" when you know how many times to loop (iterating a list, range). Use "while" when you loop until a condition changes (waiting for user input, game loops).',
        },
        {
          type: 'bullets',
          items: [
            'Indentation is mandatory — use 4 spaces consistently.',
            'range(start, stop) excludes the stop value.',
            'while loops repeat until a condition becomes False.',
            'break exits a loop early; continue skips to the next iteration.',
          ],
        },
      ],
    },
    {
      id: 'py-functions',
      title: 'Functions',
      duration: '20 min',
      objective: 'Write reusable blocks of logic with parameters and return values.',
      blocks: [
        { type: 'heading', text: 'Why Functions?' },
        {
          type: 'paragraph',
          text: 'Functions let you name a block of code and call it whenever you need it. They take inputs (parameters) and can return outputs. This is the foundation of writing clean, organized, reusable code.',
        },
        {
          type: 'analogy',
          text: 'A function is like a vending machine. You put in coins (arguments), press a button (call the function), and get a snack (return value). You don\'t need to know the internal mechanics — just what goes in and what comes out.',
        },
        {
          type: 'image',
          title: 'Functions transform inputs into outputs',
          imageType: 'function-flow',
        },
        {
          type: 'code',
          code: 'def greet(name):\\n    return f"Hello, {name}!"\\n\\nprint(greet("Ada"))\\nprint(greet("Alan"))',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Practice: Your First Function' },
        {
          type: 'playground',
          code: 'def square(n):\\n    return n * n\\n\\nresult = square(7)\\nprint(result)',
          expectedOutput: '49',
        },
        {
          type: 'stepByStep',
          title: 'Anatomy of a Function',
          steps: [
            { title: 'def keyword', description: 'Tells Python you\'re defining a new function.' },
            { title: 'Function name (square)', description: 'The name you\'ll use to call it later. Use snake_case.' },
            { title: 'Parameters (n)', description: 'Variables that receive the input values when called.' },
            { title: 'Body (return n * n)', description: 'The code that runs when the function is called.' },
            { title: 'return statement', description: 'Sends a value back to whoever called the function.' },
          ],
        },
        {
          type: 'formula',
          expression: 'def function_name(param1, param2=default): → return value',
          note: 'Default parameters make arguments optional.',
        },
        {
          type: 'callout',
          variant: 'info',
          title: 'Arguments vs Parameters',
          body: 'Parameters are the variable names in the function definition (def greet(name)). Arguments are the actual values you pass when calling it (greet("Ada")). They\'re often used interchangeably, but the distinction matters in documentation.',
        },
        {
          type: 'table',
          headers: ['Feature', 'Syntax', 'Use Case'],
          rows: [
            ['Default param', 'def f(x=10)', 'Optional arguments'],
            ['*args', 'def f(*args)', 'Variable positional args'],
            ['**kwargs', 'def f(**kw)', 'Variable keyword args'],
            ['Lambda', 'lambda x: x*2', 'Quick one-liner functions'],
          ],
        },
        {
          type: 'bullets',
          items: [
            'Functions should do one thing well.',
            'Use default parameters for optional arguments.',
            'Lambda functions: square = lambda x: x * x.',
            '*args collects extra positional arguments into a tuple.',
            '**kwargs collects extra keyword arguments into a dictionary.',
          ],
        },
      ],
    },
    {
      id: 'py-data-structures',
      title: 'Lists, Dicts, and Comprehensions',
      duration: '22 min',
      objective: 'Store and transform collections of data efficiently.',
      blocks: [
        { type: 'heading', text: 'Python Collections' },
        {
          type: 'paragraph',
          text: 'Lists are ordered, mutable sequences. Dictionaries map keys to values. Both are fundamental to every Python program and form the backbone of data manipulation.',
        },
        {
          type: 'analogy',
          text: 'A list is like a numbered shelf — items sit in order at positions 0, 1, 2... A dictionary is like a phone book — you look up a name (key) to find a number (value). No positions needed, just labels.',
        },
        {
          type: 'image',
          title: 'Lists store items at numbered index positions',
          imageType: 'list-visualization',
        },
        {
          type: 'code',
          code: 'scores = [85, 92, 78, 95, 88]\\nprint(max(scores))\\nprint(sorted(scores))',
        },
        {
          type: 'code',
          code: 'student = {"name": "Ada", "age": 30, "grade": "A"}\\nprint(student["name"])\\nprint(student.get("gpa", "N/A"))',
        },
        { type: 'divider' },
        { type: 'heading', text: 'List Comprehensions — Power in One Line' },
        {
          type: 'playground',
          code: 'nums = [1, 2, 3, 4, 5]\\nsquares = [x**2 for x in nums]\\nprint(squares)',
          expectedOutput: '[1, 4, 9, 16, 25]',
        },
        {
          type: 'formula',
          expression: '[expression for item in iterable if condition]',
          note: 'List comprehensions replace simple for-loops with one readable line.',
        },
        {
          type: 'table',
          headers: ['Structure', 'Syntax', 'Ordered?', 'Mutable?'],
          rows: [
            ['List', '[1, 2, 3]', 'Yes', 'Yes'],
            ['Tuple', '(1, 2, 3)', 'Yes', 'No'],
            ['Dict', '{"a": 1}', 'Yes (3.7+)', 'Yes'],
            ['Set', '{1, 2, 3}', 'No', 'Yes'],
          ],
        },
        {
          type: 'callout',
          variant: 'remember',
          title: 'When to Use What',
          body: 'Use lists for ordered collections you\'ll modify. Use tuples for fixed data (coordinates, RGB). Use dicts for key-value lookups. Use sets for unique items and fast membership testing.',
        },
        {
          type: 'bullets',
          items: [
            'Lists use [] and are ordered. Dicts use {} with key: value pairs.',
            'Sets use {} without values — they store unique items only.',
            'Tuples use () and are immutable (cannot be changed).',
            'Use .append(), .pop(), .insert() to modify lists.',
            'Dict comprehensions: {k: v for k, v in items}.',
          ],
        },
      ],
    },
    {
      id: 'py-file-io',
      title: 'File I/O and String Methods',
      duration: '16 min',
      objective: 'Read and write files, manipulate strings for data processing.',
      blocks: [
        { type: 'heading', text: 'Working with Files' },
        {
          type: 'paragraph',
          text: 'Reading data from files is the first step in most data science workflows. Python\'s built-in open() and string methods make this straightforward.',
        },
        {
          type: 'analogy',
          text: 'Opening a file is like checking out a library book. You open it (check out), read or write (use it), then close it (return it). The "with" statement is like an auto-return — it closes the file for you even if something goes wrong.',
        },
        {
          type: 'code',
          code: 'with open("data.txt", "w") as f:\\n    f.write("Hello, World!\\n")\\n    f.write("Python is great!")\\n\\nwith open("data.txt", "r") as f:\\n    content = f.read()\\n    print(content)',
        },
        {
          type: 'table',
          headers: ['Mode', 'Symbol', 'Description'],
          rows: [
            ['Read', '"r"', 'Read file contents (default)'],
            ['Write', '"w"', 'Write (creates or overwrites)'],
            ['Append', '"a"', 'Add to end of file'],
            ['Read+Write', '"r+"', 'Both read and write'],
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'String Power Tools' },
        {
          type: 'playground',
          code: 'text = "  Hello, Python World!  "\\nprint(text.strip())\\nprint(text.strip().lower())\\nprint(text.strip().split(", "))',
          expectedOutput: 'Hello, Python World!\nhello, python world!\n[\'Hello\', \'Python World!\']',
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'Method Chaining',
          body: 'String methods return new strings, so you can chain them: text.strip().lower().split(). Each method transforms the result of the previous one. This is a common Python pattern.',
        },
        {
          type: 'bullets',
          items: [
            'Always use "with" blocks — they close files automatically.',
            '"r" for reading, "w" for writing (overwrites), "a" for appending.',
            'f-strings: f"Value is {variable}" for formatted output.',
            '.strip() removes whitespace, .split() breaks strings into lists.',
            '.join() combines a list into a string: ", ".join(items).',
          ],
        },
      ],
    },
  ],
  "quiz": [
    { "id": "pyb-q1", "prompt": "What type is the value 3.14 in Python?", "options": ["float", "int", "str", "decimal"], "answerIndex": 0, "explanation": "Numbers with decimal points are float type in Python." },
    { "id": "pyb-q2", "prompt": "What does range(1, 5) produce?", "options": ["1, 2, 3, 4", "1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "1, 5"], "answerIndex": 0, "explanation": "range(start, stop) includes start but excludes stop." },
    { "id": "pyb-q3", "prompt": "What keyword defines a function in Python?", "options": ["def", "func", "function", "define"], "answerIndex": 0, "explanation": "Python uses 'def' followed by the function name and parentheses." },
    { "id": "pyb-q4", "prompt": "What does [x**2 for x in range(4)] produce?", "options": ["[0, 1, 4, 9]", "[1, 4, 9, 16]", "[0, 2, 4, 6]", "[1, 2, 3, 4]"], "answerIndex": 0, "explanation": "range(4) gives 0,1,2,3 and **2 squares each value." },
    { "id": "pyb-q5", "prompt": "Which data structure uses key-value pairs?", "options": ["Dictionary", "List", "Tuple", "Set"], "answerIndex": 0, "explanation": "Dictionaries store data as {key: value} pairs." },
    { "id": "pyb-q6", "prompt": "What does 'with open(file) as f' ensure?", "options": ["The file is closed automatically", "The file is encrypted", "The file is compressed", "The file is backed up"], "answerIndex": 0, "explanation": "The 'with' context manager guarantees the file is closed even if an error occurs." },
    { "id": "pyb-q7", "prompt": "What is the result of bool(0)?", "options": ["False", "True", "0", "None"], "answerIndex": 0, "explanation": "Zero is falsy in Python. bool(0) returns False." },
    { "id": "pyb-q8", "prompt": "Which method adds an item to the end of a list?", "options": ["append()", "add()", "push()", "insert()"], "answerIndex": 0, "explanation": "list.append(item) adds the item to the end. insert() requires an index." },
    { "id": "pyb-q9", "prompt": "What does 'hello'.upper() return?", "options": ["'HELLO'", "'Hello'", "'hello'", "Error"], "answerIndex": 0, "explanation": ".upper() converts all characters to uppercase." },
    { "id": "pyb-q10", "prompt": "What is the difference between a tuple and a list?", "options": ["Tuples are immutable", "Tuples are faster at appending", "Lists use ()", "Tuples allow duplicates but lists do not"], "answerIndex": 0, "explanation": "Tuples cannot be modified after creation; lists can." },
    { "id": "pyb-q11", "prompt": "What does the // operator do in Python?", "options": ["Floor (integer) division", "True division", "Modulo", "Exponentiation"], "answerIndex": 0, "explanation": "7 // 2 gives 3, not 3.5. It always rounds toward negative infinity." },
    { "id": "pyb-q12", "prompt": "Which of these is a valid f-string?", "options": ["f\"Hello {name}\"", "f\"Hello $name\"", "f\"Hello %name%\"", "f\"Hello <name>\""], "answerIndex": 0, "explanation": "f-strings use curly braces {} to embed expressions." },
    { "id": "pyb-q13", "prompt": "What does len([1, 2, 3]) return?", "options": ["3", "2", "1", "0"], "answerIndex": 0, "explanation": "len() returns the number of elements in the list." },
    { "id": "pyb-q14", "prompt": "How do you create an empty dictionary?", "options": ["{}", "[]", "()", "set()"], "answerIndex": 0, "explanation": "{} creates an empty dict. [] is an empty list, () is an empty tuple, set() is an empty set." },
    { "id": "pyb-q15", "prompt": "What is the output of print(type([]))?", "options": ["<class 'list'>", "<class 'tuple'>", "<class 'dict'>", "<class 'set'>"], "answerIndex": 0, "explanation": "[] is a list literal in Python." },
    { "id": "pyb-q16", "prompt": "What is the result of 'Python'[1:4]?", "options": ["yth", "Pyt", "tho", "hon"], "answerIndex": 0, "explanation": "Slicing [1:4] extracts characters at indices 1, 2, 3 — 'yth'." },
    { "id": "pyb-q17", "prompt": "Which keyword skips the current loop iteration?", "options": ["continue", "break", "pass", "skip"], "answerIndex": 0, "explanation": "continue moves to the next iteration without executing the rest of the loop body." },
    { "id": "pyb-q18", "prompt": "What does dict.get('key', 'default') do when 'key' is missing?", "options": ["Returns 'default'", "Raises KeyError", "Returns None", "Inserts 'key'"], "answerIndex": 0, "explanation": "dict.get(key, default) returns the default value instead of raising KeyError." },
    { "id": "pyb-q19", "prompt": "Which built-in function converts a value to a string?", "options": ["str()", "string()", "toString()", "text()"], "answerIndex": 0, "explanation": "str() is the built-in constructor for the string type." },
    { "id": "pyb-q20", "prompt": "What is the output of 2 ** 3 ** 2?", "options": ["512", "64", "216", "8"], "answerIndex": 0, "explanation": "Exponentiation is right-associative: 3**2=9, then 2**9=512." },
    { "id": "pyb-q21", "prompt": "What does the 'in' keyword do when used with a list?", "options": ["Checks membership", "Loops over items", "Imports a module", "Assigns a value"], "answerIndex": 0, "explanation": "'x in lst' returns True if x is present in lst." },
    { "id": "pyb-q22", "prompt": "How do you remove and return the last element of a list?", "options": ["list.pop()", "list.remove()", "list.delete()", "del list[-1]"], "answerIndex": 0, "explanation": "pop() removes and returns the last element by default." },
    { "id": "pyb-q23", "prompt": "What will int('3.14') raise?", "options": ["ValueError", "TypeError", "SyntaxError", "FloatError"], "answerIndex": 0, "explanation": "int() cannot parse a string with a decimal point — that raises ValueError." },
    { "id": "pyb-q24", "prompt": "What does sorted([3,1,2]) return?", "options": ["[1,2,3]", "[3,2,1]", "None", "[3,1,2]"], "answerIndex": 0, "explanation": "sorted() returns a new sorted list and does not modify the original." },
    { "id": "pyb-q25", "prompt": "What is the Pythonic way to check if a list is empty?", "options": ["if not my_list:", "if my_list == []:", "if len(my_list) == 0:", "if my_list is None:"], "answerIndex": 0, "explanation": "Empty containers are falsy. 'if not my_list:' is the idiomatic check." },
    { "id": "pyb-q26", "prompt": "What does the % operator return for 10 % 3?", "options": ["1", "3", "0", "2"], "answerIndex": 0, "explanation": "10 divided by 3 is 3 remainder 1. % returns the remainder." },
    { "id": "pyb-q27", "prompt": "Which of these creates a set?", "options": ["{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)", "<1, 2, 3>"], "answerIndex": 0, "explanation": "Curly braces with no key:value pairs create a set." },
    { "id": "pyb-q28", "prompt": "What is the output of 'abc' * 3?", "options": ["'abcabcabc'", "Error", "9", "['abc','abc','abc']"], "answerIndex": 0, "explanation": "String repetition with * repeats the string n times." },
    { "id": "pyb-q29", "prompt": "Which keyword exits a loop immediately?", "options": ["break", "continue", "exit", "return"], "answerIndex": 0, "explanation": "break terminates the nearest enclosing loop immediately." },
    { "id": "pyb-q30", "prompt": "What does list.sort() return?", "options": ["None", "The sorted list", "A new list", "True"], "answerIndex": 0, "explanation": "list.sort() sorts in-place and returns None. Use sorted() to get a new list." },
    { "id": "pyb-q31", "prompt": "What is the result of bool('')?", "options": ["False", "True", "None", "Error"], "answerIndex": 0, "explanation": "An empty string is falsy in Python." },
    { "id": "pyb-q32", "prompt": "How do you access the last element of a list named lst?", "options": ["lst[-1]", "lst[last]", "lst.last()", "lst[len(lst)]"], "answerIndex": 0, "explanation": "Negative indexing: -1 refers to the last element." },
    { "id": "pyb-q33", "prompt": "What does 'hello world'.split() return?", "options": ["['hello','world']", "('hello','world')", "{'hello','world'}", "hello world"], "answerIndex": 0, "explanation": "split() with no args splits on any whitespace and returns a list." },
    { "id": "pyb-q34", "prompt": "Which of these is NOT a valid variable name?", "options": ["2score", "score2", "_score", "Score"], "answerIndex": 0, "explanation": "Variable names cannot start with a digit." },
    { "id": "pyb-q35", "prompt": "What does enumerate(['a','b','c']) give on each iteration?", "options": ["(index, value) tuples", "Just the index", "Just the value", "A dict"], "answerIndex": 0, "explanation": "enumerate yields (0,'a'), (1,'b'), (2,'c') — index and value together." },
    { "id": "pyb-q36", "prompt": "What is the output of max([3, 1, 4, 1, 5, 9])?", "options": ["9", "5", "3", "1"], "answerIndex": 0, "explanation": "max() returns the largest value in the iterable." },
    { "id": "pyb-q37", "prompt": "What does '   hi   '.strip() return?", "options": ["'hi'", "'   hi   '", "'hi   '", "'   hi'"], "answerIndex": 0, "explanation": "strip() removes leading and trailing whitespace." },
    { "id": "pyb-q38", "prompt": "What keyword is used to handle exceptions?", "options": ["except", "catch", "handle", "error"], "answerIndex": 0, "explanation": "Python uses try/except — not try/catch like Java or JavaScript." },
    { "id": "pyb-q39", "prompt": "What is the output of list(range(0, 10, 3))?", "options": ["[0,3,6,9]", "[0,3,6,9,12]", "[3,6,9]", "[0,3,6]"], "answerIndex": 0, "explanation": "range(0,10,3) starts at 0, steps by 3, stops before 10: 0,3,6,9." },
    { "id": "pyb-q40", "prompt": "What does the 'pass' statement do?", "options": ["Does nothing — a placeholder", "Exits the function", "Skips one loop step", "Imports a module"], "answerIndex": 0, "explanation": "pass is a no-op used as a placeholder where Python syntax requires a statement." },
    { "id": "pyb-q41", "prompt": "What is the output of round(3.567, 2)?", "options": ["3.57", "3.56", "3.6", "4.0"], "answerIndex": 0, "explanation": "round(n, 2) rounds to 2 decimal places. 3.567 rounds to 3.57." },
    { "id": "pyb-q42", "prompt": "Which method returns all keys in a dictionary?", "options": ["dict.keys()", "dict.values()", "dict.items()", "dict.all()"], "answerIndex": 0, "explanation": "dict.keys() returns a view of all keys. Use list() to convert to a list." },
    { "id": "pyb-q43", "prompt": "What does 'python'.find('th') return?", "options": ["2", "1", "3", "-1"], "answerIndex": 0, "explanation": "'th' starts at index 2 in 'python'. find() returns the starting index." },
    { "id": "pyb-q44", "prompt": "What is the output of 5 == 5.0 in Python?", "options": ["True", "False", "TypeError", "None"], "answerIndex": 0, "explanation": "== compares values. 5 and 5.0 are equal in value even though types differ." },
    { "id": "pyb-q45", "prompt": "How do you add all items from list b into list a?", "options": ["a.extend(b)", "a.append(b)", "a.add(b)", "a.insert(b)"], "answerIndex": 0, "explanation": "extend() adds each element of b individually. append(b) would add the whole list as one element." },
    { "id": "pyb-q46", "prompt": "What does zip([1,2],[3,4]) produce?", "options": ["[(1,3),(2,4)]", "[[1,3],[2,4]]", "[1,2,3,4]", "(1,2,3,4)"], "answerIndex": 0, "explanation": "zip pairs up elements from each iterable into tuples." },
    { "id": "pyb-q47", "prompt": "What does the 'global' keyword do inside a function?", "options": ["Allows modifying a module-level variable", "Creates a new global module", "Imports everything", "Deletes a variable"], "answerIndex": 0, "explanation": "Without 'global', assigning to a name inside a function creates a local variable." },
    { "id": "pyb-q48", "prompt": "What is the output of [1,2,3] + [4,5]?", "options": ["[1,2,3,4,5]", "[5,7]", "Error", "[[1,2,3],[4,5]]"], "answerIndex": 0, "explanation": "+ on lists concatenates them into a new list." },
    { "id": "pyb-q49", "prompt": "What does 'banana'.count('a') return?", "options": ["3", "2", "1", "0"], "answerIndex": 0, "explanation": "There are three 'a's in 'banana'." },
    { "id": "pyb-q50", "prompt": "What is the output of bool([]) and bool([0])?", "options": ["False and True", "True and True", "False and False", "True and False"], "answerIndex": 0, "explanation": "An empty list [] is falsy. [0] has one element (even if 0) so it is truthy." },

    { "id": "pyb-q51", "prompt": "What does None == False evaluate to in Python?", "options": ["False", "True", "TypeError", "None"], "answerIndex": 0, "explanation": "None is not equal to False. None == False is False; use 'is None' to test for None." },
    { "id": "pyb-q52", "prompt": "What is the output of 0.1 + 0.2 == 0.3 in Python?", "options": ["False", "True", "TypeError", "ValueError"], "answerIndex": 0, "explanation": "Floating-point arithmetic is imprecise; 0.1 + 0.2 gives 0.30000000000000004. Use math.isclose() instead." },
    { "id": "pyb-q53", "prompt": "What does 'hello'.replace('l', 'r') return?", "options": ["'herro'", "'hero'", "'helo'", "Error"], "answerIndex": 0, "explanation": "replace() replaces ALL occurrences — both 'l's become 'r'." },
    { "id": "pyb-q54", "prompt": "What happens when you multiply a list: [0] * 3?", "options": ["[0, 0, 0]", "[0, 3]", "[0]", "Error"], "answerIndex": 0, "explanation": "* on a list repeats its elements n times, returning a new list." },
    { "id": "pyb-q55", "prompt": "What does list.index(value) raise if the value is not found?", "options": ["ValueError", "IndexError", "KeyError", "LookupError"], "answerIndex": 0, "explanation": "list.index() raises ValueError when the value is absent — not IndexError." },
    { "id": "pyb-q56", "prompt": "What is the output of 'abc'[-1]?", "options": ["'c'", "'a'", "'b'", "IndexError"], "answerIndex": 0, "explanation": "Negative index -1 refers to the last character of the string." },
    { "id": "pyb-q57", "prompt": "Which of these checks identity (same object), not equality?", "options": ["is", "==", "===", "eq()"], "answerIndex": 0, "explanation": "'is' checks if two names point to the exact same object in memory." },
    { "id": "pyb-q58", "prompt": "What does '\\n' represent in a Python string?", "options": ["A newline character", "A tab character", "A backslash", "A null byte"], "answerIndex": 0, "explanation": "'\\n' is the escape sequence for a newline (line break) character." },
    { "id": "pyb-q59", "prompt": "What is the output of int(True) + int(False)?", "options": ["1", "2", "0", "TypeError"], "answerIndex": 0, "explanation": "True converts to 1 and False to 0; int(True)+int(False) = 1." },
    { "id": "pyb-q60", "prompt": "What does dict.items() return?", "options": ["View of (key, value) tuples", "List of keys", "List of values", "A new dict"], "answerIndex": 0, "explanation": "dict.items() returns a view object of (key, value) pairs, useful for iteration." },
    { "id": "pyb-q61", "prompt": "What is the output of print('a', 'b', sep='-')?", "options": ["a-b", "a b", "ab", "a-b-"], "answerIndex": 0, "explanation": "The sep parameter defines the separator between print() arguments. Default is space." },
    { "id": "pyb-q62", "prompt": "What does list.clear() do?", "options": ["Removes all elements, leaving an empty list", "Deletes the list variable", "Returns a new empty list", "Raises an error on empty list"], "answerIndex": 0, "explanation": "clear() empties the list in-place. The list object still exists, just with no items." },
    { "id": "pyb-q63", "prompt": "What is the output of 'hello' in 'hello world'?", "options": ["True", "False", "'hello'", "Error"], "answerIndex": 0, "explanation": "'in' checks for substring membership in strings, returning True or False." },
    { "id": "pyb-q64", "prompt": "What does range(5, 0, -1) produce?", "options": ["5, 4, 3, 2, 1", "5, 4, 3, 2, 1, 0", "4, 3, 2, 1", "0, 1, 2, 3, 4"], "answerIndex": 0, "explanation": "A negative step counts down. range(5,0,-1) gives 5,4,3,2,1 — stops before 0." },
    { "id": "pyb-q65", "prompt": "What is the output of min('banana')?", "options": ["'a'", "'b'", "'n'", "Error"], "answerIndex": 0, "explanation": "min() on a string compares characters by ASCII value. 'a' (97) is less than 'b' (98)." },
    { "id": "pyb-q66", "prompt": "What does ','.join(['a','b','c']) return?", "options": ["'a,b,c'", "['a,b,c']", "'a','b','c'", "Error"], "answerIndex": 0, "explanation": "str.join(iterable) concatenates items with the string as separator." },
    { "id": "pyb-q67", "prompt": "What is the value of x after: x = 5; x += 3?", "options": ["8", "5", "3", "53"], "answerIndex": 0, "explanation": "+= is shorthand for x = x + 3. So x becomes 5 + 3 = 8." },
    { "id": "pyb-q68", "prompt": "What does 'Python'.startswith('Py') return?", "options": ["True", "False", "'Py'", "1"], "answerIndex": 0, "explanation": "startswith() returns True if the string begins with the given prefix." },
    { "id": "pyb-q69", "prompt": "What exception is raised when you access an out-of-range list index?", "options": ["IndexError", "KeyError", "ValueError", "RangeError"], "answerIndex": 0, "explanation": "Accessing lst[100] on a short list raises IndexError." },
    { "id": "pyb-q70", "prompt": "What is the output of type(1 / 2)?", "options": ["<class 'float'>", "<class 'int'>", "<class 'fraction'>", "<class 'number'>"], "answerIndex": 0, "explanation": "In Python 3, / always returns float even for two integers. Use // for integer division." },
    { "id": "pyb-q71", "prompt": "What does the walrus operator do? (e.g. while chunk := f.read(1024))", "options": ["Assigns and returns a value in one expression", "Compares with strict equality", "Divides and assigns", "Creates a generator"], "answerIndex": 0, "explanation": ":= (Python 3.8+) assigns the value of the expression AND returns it, useful inside conditions." },
    { "id": "pyb-q72", "prompt": "What is the output of abs(-7.5)?", "options": ["7.5", "-7.5", "7", "8"], "answerIndex": 0, "explanation": "abs() returns the absolute (non-negative) value, preserving the float type." },
    { "id": "pyb-q73", "prompt": "What does [1, 2, 3].copy() return?", "options": ["A shallow copy of the list", "The same list object", "A deep copy", "None"], "answerIndex": 0, "explanation": ".copy() creates a new list with the same top-level elements. Nested objects are still shared." },
    { "id": "pyb-q74", "prompt": "What is the output of ('a',) == ('a')?", "options": ["False", "True", "TypeError", "SyntaxError"], "answerIndex": 0, "explanation": "('a',) is a one-element tuple; ('a') is just 'a' with parentheses — they are not equal." },
    { "id": "pyb-q75", "prompt": "What does any([False, False, True]) return?", "options": ["True", "False", "[True]", "None"], "answerIndex": 0, "explanation": "any() returns True if at least one element is truthy." }
  ],
  "practice": [
    { "id": "pyb-p1", "title": "Sum of Squares", "prompt": "Use a list comprehension to create squares of 1-5 and print the sum.", "starterCode": "squares = [x**2 for x in range(1, 6)]\nprint(sum(squares))", "expectedOutput": "55", "hint": "range(1,6) gives 1-5. Sum of 1+4+9+16+25=55." },
    { "id": "pyb-p2", "title": "Grade Calculator", "prompt": "Write an if/elif/else to assign a letter grade for score = 85.", "starterCode": "score = 85\nif score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"\nelse:\n    grade = \"C\"\nprint(grade)", "expectedOutput": "B", "hint": "85 is >=80 but <90, so it falls into the elif branch." },
    { "id": "pyb-p3", "title": "Dictionary Access", "prompt": "Create a student dict and print the name.", "starterCode": "student = {\"name\": \"Ada\", \"age\": 30}\nprint(student[\"name\"])", "expectedOutput": "Ada", "hint": "Use square brackets with the key string." },
    { "id": "pyb-p4", "title": "Function Return", "prompt": "Write a function that doubles a number and print the result for 21.", "starterCode": "def double(n):\n    return n * 2\n\nprint(double(21))", "expectedOutput": "42", "hint": "Return n * 2." },
    { "id": "pyb-p5", "title": "String Methods", "prompt": "Strip whitespace and convert to uppercase.", "starterCode": "text = \"  hello world  \"\nprint(text.strip().upper())", "expectedOutput": "HELLO WORLD", "hint": ".strip() removes spaces, .upper() capitalizes." },
    { "id": "pyb-p6", "title": "Loop Accumulator", "prompt": "Use a for loop to sum numbers from 1 to 10.", "starterCode": "total = 0\nfor i in range(1, 11):\n    total += i\nprint(total)", "expectedOutput": "55", "hint": "range(1, 11) gives 1 through 10." },
    { "id": "pyb-p7", "title": "Count Vowels", "prompt": "Count how many vowels are in 'machine learning'.", "starterCode": "text = \"machine learning\"\nvowels = \"aeiou\"\ncount = sum(1 for c in text if c in vowels)\nprint(count)", "expectedOutput": "6", "hint": "Loop through each character and check if it is in the vowels string." },
    { "id": "pyb-p8", "title": "Reverse a String", "prompt": "Reverse 'Python' using slicing.", "starterCode": "word = \"Python\"\nprint(word[::-1])", "expectedOutput": "nohtyP", "hint": "[::-1] is a slice with step=-1." },
    { "id": "pyb-p9", "title": "Filter Evens", "prompt": "Use a list comprehension to get even numbers from 1 to 20.", "starterCode": "evens = [x for x in range(1, 21) if x % 2 == 0]\nprint(evens)", "expectedOutput": "[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]", "hint": "x % 2 == 0 is True when x is even." },
    { "id": "pyb-p10", "title": "Tuple Unpacking", "prompt": "Swap x=10, y=20 using tuple unpacking and print both.", "starterCode": "x, y = 10, 20\nx, y = y, x\nprint(x, y)", "expectedOutput": "20 10", "hint": "Python evaluates the right side first, then assigns." },
    { "id": "pyb-p11", "title": "Set Deduplication", "prompt": "Remove duplicates from a list using a set, then sort and print.", "starterCode": "nums = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3]\nunique = sorted(set(nums))\nprint(unique)", "expectedOutput": "[1, 2, 3, 4, 5, 6, 9]", "hint": "set() removes duplicates, sorted() returns a sorted list." },
    { "id": "pyb-p12", "title": "FizzBuzz", "prompt": "Print 1-15. Print 'Fizz' for multiples of 3, 'Buzz' for 5, 'FizzBuzz' for both.", "starterCode": "for i in range(1, 16):\n    if i % 15 == 0:\n        print(\"FizzBuzz\")\n    elif i % 3 == 0:\n        print(\"Fizz\")\n    elif i % 5 == 0:\n        print(\"Buzz\")\n    else:\n        print(i)", "expectedOutput": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz", "hint": "Check 15 first, then 3, then 5. Order matters!" },
    { "id": "pyb-p13", "title": "Word Frequency", "prompt": "Count how many times each word appears in a sentence and print the dict.", "starterCode": "sentence = \"the cat sat on the mat the cat\"\nfreq = {}\nfor word in sentence.split():\n    freq[word] = freq.get(word, 0) + 1\nprint(freq)", "expectedOutput": "{'the': 3, 'cat': 2, 'sat': 1, 'on': 1, 'mat': 1}", "hint": "dict.get(word, 0) returns 0 if the word is not yet in the dict." },
    { "id": "pyb-p14", "title": "Palindrome Check", "prompt": "Write a function is_palindrome(s) that returns True if s reads the same forwards and backwards.", "starterCode": "def is_palindrome(s):\n    return s == s[::-1]\n\nprint(is_palindrome(\"racecar\"))\nprint(is_palindrome(\"hello\"))", "expectedOutput": "True\nFalse", "hint": "Compare the string to its reverse using slicing [::-1]." },
    { "id": "pyb-p15", "title": "Multiplication Table", "prompt": "Print the multiplication table for 5 (5x1 through 5x10) using a for loop.", "starterCode": "for i in range(1, 11):\n    print(f\"5 x {i} = {5 * i}\")", "expectedOutput": "5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45\n5 x 10 = 50", "hint": "Use range(1, 11) and f-strings." },
    { "id": "pyb-p16", "title": "Safe Division", "prompt": "Write safe_divide(a, b) that returns 'Cannot divide by zero' when b is 0.", "starterCode": "def safe_divide(a, b):\n    if b == 0:\n        return \"Cannot divide by zero\"\n    return a / b\n\nprint(safe_divide(10, 2))\nprint(safe_divide(5, 0))", "expectedOutput": "5.0\nCannot divide by zero", "hint": "Use an if statement to check b before dividing." },
    { "id": "pyb-p17", "title": "Flatten a List", "prompt": "Use a list comprehension to flatten [[1,2],[3,4],[5,6]] into a single list.", "starterCode": "matrix = [[1,2],[3,4],[5,6]]\nflat = [n for row in matrix for n in row]\nprint(flat)", "expectedOutput": "[1, 2, 3, 4, 5, 6]", "hint": "Nest two for clauses: for row in matrix, then for n in row." },
    { "id": "pyb-p18", "title": "Lambda Sort", "prompt": "Sort a list of tuples (name, score) by score descending and print the top scorer.", "starterCode": "students = [(\"Alice\", 85), (\"Bob\", 92), (\"Carol\", 78)]\nstudents.sort(key=lambda s: s[1], reverse=True)\nprint(students[0][0])", "expectedOutput": "Bob", "hint": "lambda s: s[1] extracts the score for comparison. reverse=True sorts highest first." },
    { "id": "pyb-p19", "title": "File Write & Read", "prompt": "Write three names to a file then read and print them.", "starterCode": "with open(\"names.txt\", \"w\") as f:\n    f.write(\"Alice\\nBob\\nCarol\\n\")\n\nwith open(\"names.txt\", \"r\") as f:\n    for line in f:\n        print(line.strip())", "expectedOutput": "Alice\nBob\nCarol", "hint": "Use 'w' mode to write, 'r' mode to read. strip() removes the newline." },
    { "id": "pyb-p20", "title": "Default Argument", "prompt": "Write greet(name, greeting='Hello') and call it with and without a greeting.", "starterCode": "def greet(name, greeting=\"Hello\"):\n    return f\"{greeting}, {name}!\"\n\nprint(greet(\"Ada\"))\nprint(greet(\"Turing\", \"Hi\"))", "expectedOutput": "Hello, Ada!\nHi, Turing!", "hint": "Default arguments are used when the caller does not provide a value." },
    {
      "id": "pyb-p21", "title": "Mutable Default Trap", "prompt": "Fix the bug: the function below shares state between calls because the default is mutable. Fix it so each call gets its own fresh list.",
      "starterCode": "def add_item(item, lst=None):\n    if lst is None:\n        lst = []\n    lst.append(item)\n    return lst\n\nprint(add_item(1))\nprint(add_item(2))",
      "expectedOutput": "[1]\n[2]",
      "hint": "Never use mutable objects (lists, dicts) as default argument values. Use None and create inside the function."
    },
    {
      "id": "pyb-p22", "title": "Nested Dict Access", "prompt": "Given a nested dict, safely retrieve a deeply nested value without raising KeyError.",
      "starterCode": "data = {\"user\": {\"profile\": {\"city\": \"London\"}}}\ncity = data.get(\"user\", {}).get(\"profile\", {}).get(\"city\", \"Unknown\")\nprint(city)",
      "expectedOutput": "London",
      "hint": "Chain .get() calls, each with an empty dict as the default, to avoid KeyError on missing keys."
    },
    {
      "id": "pyb-p23", "title": "String Formatting", "prompt": "Format a float to exactly 2 decimal places using an f-string.",
      "starterCode": "price = 9.5\nprint(f\"${price:.2f}\")",
      "expectedOutput": "$9.50",
      "hint": "Use :.2f inside the curly braces to specify two decimal places."
    },
    {
      "id": "pyb-p24", "title": "Multiple Return Values", "prompt": "Write a function min_max(lst) that returns the minimum and maximum of a list as a tuple.",
      "starterCode": "def min_max(lst):\n    return min(lst), max(lst)\n\nlo, hi = min_max([3, 1, 4, 1, 5, 9])\nprint(lo, hi)",
      "expectedOutput": "1 9",
      "hint": "Return two values separated by a comma — Python packs them into a tuple automatically."
    },
    {
      "id": "pyb-p25", "title": "While Loop Counter", "prompt": "Use a while loop to count down from 5 to 1 and print each number.",
      "starterCode": "n = 5\nwhile n > 0:\n    print(n)\n    n -= 1",
      "expectedOutput": "5\n4\n3\n2\n1",
      "hint": "Decrement n inside the loop body to avoid an infinite loop."
    }
  ],
};
