import { Workflow } from 'lucide-react-native';
import type { CourseModule } from '../types/course';

export const pythonAdvancedCourse: CourseModule = {
  id: 'python-advanced',
  title: 'Python Advanced',
  subtitle: 'OOP, decorators, generators, error handling',
  color: '#6B4C9A',
  accent: '#EDE5F7',
  Icon: Workflow,
  history: {
    founder: 'Guido van Rossum',
    released: '1991',
    summary:
      'Python\'s advanced features — classes, generators, decorators — let you build large, maintainable AI projects. Most ML frameworks are built on these patterns.',
  },
  concepts: [
    'Classes, objects, and __init__',
    'Inheritance and method overriding',
    'Decorators as function wrappers',
    'Generators and yield for lazy iteration',
    'try / except / finally error handling',
    'Context managers (with statement)',
    'Modules and packages',
    'Type hints for documentation',
  ],
  lessons: [
    {
      id: 'pya-oop',
      title: 'Classes and OOP',
      duration: '22 min',
      objective: 'Model real-world entities with classes, attributes, and methods.',
      blocks: [
        { type: 'heading', text: 'Object-Oriented Programming (OOP)' },
        {
          type: 'paragraph',
          text: 'As your Python projects grow from small scripts to massive ML frameworks, you need a way to organize related variables and functions. A `class` serves as a blueprint for creating highly organized, reusable objects.',
        },
        {
          type: 'analogy',
          text: 'Think of a class as the architectural blueprint of a house. The blueprint defines where the rooms and doors go. An object (instance) is the actual physical house built from that blueprint. You can build many identical houses (objects) from one single blueprint (class).',
        },
        {
          type: 'stepByStep',
          title: 'Creating and Using a Class',
          steps: [
            { title: 'Define the Class', description: 'Use the `class` keyword followed by a capitalized name.' },
            { title: 'Write the Constructor', description: 'The `__init__` method runs automatically to set up the object\'s initial state.' },
            { title: 'Create Instances', description: 'Call the class name like a function to create a unique, independent object in memory.' },
          ],
        },
        { type: 'divider' },
        { type: 'heading', text: 'Building a Neural Class' },
        {
          type: 'playground',
          code: 'class Neuron:\n    def __init__(self, weight, bias):\n        # self refers to the specific instance\n        self.weight = weight\n        self.bias = bias\n\n    def forward(self, x):\n        return self.weight * x + self.bias\n\n# Creating two distinct neurons\nn1 = Neuron(0.5, 2)\nn2 = Neuron(1.5, -1)\n\nprint(f"Neuron 1 output: {n1.forward(10)}")\nprint(f"Neuron 2 output: {n2.forward(10)}")',
          expectedOutput: 'Neuron 1 output: 7.0\nNeuron 2 output: 14.0',
        },
        {
          type: 'callout',
          variant: 'remember',
          title: 'The Magic of `self`',
          body: 'When defining methods inside a class, the first parameter must always be `self`. Python automatically passes the specific object instance into `self` so the method knows whose data it is modifying.',
        },
      ],
    },
    {
      id: 'pya-decorators',
      title: 'Decorators and Generators',
      duration: '24 min',
      objective: 'Wrap functions with decorators and produce values lazily with generators.',
      blocks: [
        { type: 'heading', text: 'Decorators: Function Wrappers' },
        {
          type: 'paragraph',
          text: 'A decorator allows you to modify or enhance the behavior of a function without permanently changing its source code. It is essentially a function that takes another function as an argument and returns an updated function.',
        },
        {
          type: 'analogy',
          text: 'Imagine a decorator as a gift wrapping service. You hand them your plain box (the original function), and they hand it back covered in beautiful paper with a bow (the wrapped function), but the contents inside remain exactly the same.',
        },
        {
          type: 'playground',
          code: 'def timer(func):\n    def wrapper(*args):\n        print(f"Starting {func.__name__}...")\n        result = func(*args)\n        print("Finished!")\n        return result\n    return wrapper\n\n@timer\ndef add(a, b):\n    return a + b\n\nprint(f"Result: {add(3, 4)}")',
          expectedOutput: 'Starting add...\nFinished!\nResult: 7',
        },
        { type: 'divider' },
        { type: 'heading', text: 'Generators: Lazy Sequences' },
        {
          type: 'paragraph',
          text: 'When training AI models on billions of images, you cannot load the entire dataset into memory at once. Generators solve this by using the `yield` keyword to produce one item at a time, pausing execution until the next item is requested.',
        },
        {
          type: 'table',
          headers: ['Concept', 'Keyword', 'Memory Usage', 'Best For'],
          rows: [
            ['Standard Function', 'return', 'High (Returns all data)', 'Small lists'],
            ['Generator', 'yield', 'Extremely Low', 'Massive datasets (streaming)'],
          ],
        },
        {
          type: 'playground',
          code: 'def fibonacci(limit):\n    a, b = 0, 1\n    for _ in range(limit):\n        yield a\n        a, b = b, a + b\n\n# The generator yields one value per iteration\nfor num in fibonacci(5):\n    print(num)',
          expectedOutput: '0\n1\n1\n2\n3',
        },
        {
          type: 'callout',
          variant: 'tip',
          title: 'Yield Pauses State',
          body: 'Unlike `return` which instantly terminates a function, `yield` merely pauses it. When the generator is called again, it resumes executing immediately after the `yield` statement with all variables completely intact.',
        },
      ],
    },
    {
      id: 'pya-errors',
      title: 'Error Handling',
      duration: '18 min',
      objective: 'Write robust code that handles failures gracefully.',
      blocks: [
        { type: 'heading', text: 'Guarding Against Crashes' },
        {
          type: 'paragraph',
          text: 'Production software interacts with unpredictable environments (missing network connections, corrupt files, unexpected user inputs). Instead of allowing the program to crash, Python allows you to "catch" these errors gracefully using `try / except` blocks.',
        },
        {
          type: 'diagram',
          title: 'Try/Except Flow',
          boxes: [
            { id: 'try', x: 70, y: 10, width: 90, height: 40, label: 'Try Block', color: '#2B6CB0' },
            { id: 'pass', x: 20, y: 80, width: 70, height: 40, label: 'Success', color: '#1D7A57' },
            { id: 'fail', x: 140, y: 80, width: 70, height: 40, label: 'Exception', color: '#E44D6E' },
          ],
          arrows: [
            { from: 'try', to: 'pass', label: 'Works' },
            { from: 'try', to: 'fail', label: 'Crashes' },
          ],
          height: 140,
        },
        {
          type: 'playground',
          code: 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero!"\n    finally:\n        print("Cleanup: Operation attempted.")\n\nprint(safe_divide(10, 2))\nprint(safe_divide(10, 0))',
          expectedOutput: 'Cleanup: Operation attempted.\n5.0\nCleanup: Operation attempted.\nCannot divide by zero!',
        },
        {
          type: 'callout',
          variant: 'warning',
          title: 'Avoid Bare Exceptions',
          body: 'Never use a bare `except:` without specifying the error type. Doing so will catch system exit commands and keyboard interrupts, making your program impossible to stop. Always specify the error (e.g. `except ValueError:`).',
        },
      ],
    },
  ],
  "quiz": [
    { "id": "pya-q1", "prompt": "What does __init__ do in a Python class?", "options": ["Initializes a new object", "Deletes an object", "Imports a module", "Defines a global variable"], "answerIndex": 0, "explanation": "__init__ is the constructor — it runs when you create an instance." },
    { "id": "pya-q2", "prompt": "What does the self parameter refer to?", "options": ["The current object instance", "The class itself", "The parent class", "A global variable"], "answerIndex": 0, "explanation": "self is a reference to the specific object calling the method." },
    { "id": "pya-q3", "prompt": "What does yield do in a function?", "options": ["Pauses and produces a value", "Ends the function", "Raises an error", "Imports a module"], "answerIndex": 0, "explanation": "yield produces a value and suspends the function state until next() is called." },
    { "id": "pya-q4", "prompt": "What is a decorator?", "options": ["A function that wraps another function", "A CSS class", "A type hint", "A loop construct"], "answerIndex": 0, "explanation": "Decorators take a function, add behavior, and return a new function." },
    { "id": "pya-q5", "prompt": "Which block always runs, even if an error occurs?", "options": ["finally", "except", "else", "try"], "answerIndex": 0, "explanation": "finally runs after try/except regardless of whether an error occurred." },
    { "id": "pya-q6", "prompt": "What does class Dog(Animal) mean?", "options": ["Dog inherits from Animal", "Dog is inside Animal", "Dog deletes Animal", "Dog is a module"], "answerIndex": 0, "explanation": "Parentheses after the class name indicate inheritance from the parent class." },
    { "id": "pya-q7", "prompt": "What makes generators memory-efficient?", "options": ["They produce values one at a time", "They compress data", "They run on GPU", "They use less disk space"], "answerIndex": 0, "explanation": "Generators yield items lazily instead of storing the entire sequence in memory." },
    { "id": "pya-q8", "prompt": "How do you catch a specific error type?", "options": ["except ValueError:", "catch ValueError:", "handle ValueError:", "error ValueError:"], "answerIndex": 0, "explanation": "Python uses 'except ErrorType:' to catch specific exception types." },
    { "id": "pya-q9", "prompt": "What is the purpose of __name__ == '__main__'?", "options": ["Run code only when the file is executed directly", "Import all modules", "Define the main class", "Set the file name"], "answerIndex": 0, "explanation": "This guard prevents code from running when the file is imported as a module." },
    { "id": "pya-q10", "prompt": "What does pip install do?", "options": ["Installs a third-party package", "Creates a new file", "Compiles Python to C", "Starts a web server"], "answerIndex": 0, "explanation": "pip is Python's package installer for downloading libraries from PyPI." },
    { "id": "pya-q11", "prompt": "What does @staticmethod mean?", "options": ["Method with no access to instance or class", "Method bound to the class", "Method that runs at import time", "Method that cannot return a value"], "answerIndex": 0, "explanation": "A static method does not receive self or cls — it is a plain function scoped inside a class." },
    { "id": "pya-q12", "prompt": "What is the output of list(map(str, [1, 2, 3]))?", "options": ["['1','2','3']", "[1,2,3]", "['str','str','str']", "Error"], "answerIndex": 0, "explanation": "map applies str() to each element, converting integers to strings." },
    { "id": "pya-q13", "prompt": "Which dunder method is called by len(obj)?", "options": ["__len__", "__size__", "__count__", "__length__"], "answerIndex": 0, "explanation": "Python calls obj.__len__() when you write len(obj)." },
    { "id": "pya-q14", "prompt": "What does super().__init__() do inside a child class?", "options": ["Calls the parent class constructor", "Creates a new instance", "Overrides the parent method", "Deletes the parent class"], "answerIndex": 0, "explanation": "super() returns a proxy for the parent class; calling __init__() on it runs the parent's constructor." },
    { "id": "pya-q15", "prompt": "What is a closure in Python?", "options": ["A function that captures variables from its enclosing scope", "A class that cannot be inherited", "A sealed module", "A type of generator"], "answerIndex": 0, "explanation": "Closures remember the environment (variables) in which they were created." },
    { "id": "pya-q16", "prompt": "What does asyncio.gather() do?", "options": ["Runs multiple coroutines concurrently", "Cancels all running tasks", "Creates a new event loop", "Converts a function to async"], "answerIndex": 0, "explanation": "asyncio.gather() schedules all given coroutines and runs them concurrently, returning their results." },
    { "id": "pya-q17", "prompt": "What is the difference between __str__ and __repr__?", "options": ["__str__ is for users, __repr__ is for developers/debugging", "__repr__ is for users, __str__ is for debugging", "They are identical", "__str__ is only for numbers"], "answerIndex": 0, "explanation": "__str__ should be readable; __repr__ should be unambiguous and ideally recreatable." },
    { "id": "pya-q18", "prompt": "Which of these creates a generator expression?", "options": ["(x**2 for x in range(5))", "[x**2 for x in range(5)]", "{x**2 for x in range(5)}", "gen(x**2 for x in range(5))"], "answerIndex": 0, "explanation": "Round parentheses with a comprehension-style expression create a generator." },
    { "id": "pya-q19", "prompt": "What does functools.partial() do?", "options": ["Freezes some function arguments to create a new callable", "Splits a function into parts", "Makes a function run in parallel", "Caches a function result"], "answerIndex": 0, "explanation": "partial(fn, arg) returns a new function with arg pre-filled." },
    { "id": "pya-q20", "prompt": "What keyword is used to define an async function?", "options": ["async def", "def async", "await def", "coroutine def"], "answerIndex": 0, "explanation": "'async def' declares a coroutine function that can use await inside it." },
    { "id": "pya-q21", "prompt": "What does @classmethod receive as its first argument?", "options": ["The class (cls)", "The instance (self)", "No argument", "The module"], "answerIndex": 0, "explanation": "cls refers to the class itself, not an instance. Useful for alternative constructors." },
    { "id": "pya-q22", "prompt": "What exception does next() raise when a generator is exhausted?", "options": ["StopIteration", "GeneratorExit", "IndexError", "RuntimeError"], "answerIndex": 0, "explanation": "StopIteration signals that the iterator has no more items. for loops catch this automatically." },
    { "id": "pya-q23", "prompt": "What does yield from sub_gen() do?", "options": ["Delegates iteration to sub_gen", "Imports sub_gen", "Runs sub_gen in a thread", "Caches sub_gen output"], "answerIndex": 0, "explanation": "'yield from' delegates to a sub-generator, transparently forwarding values and exceptions." },
    { "id": "pya-q24", "prompt": "Which module provides the @contextmanager decorator?", "options": ["contextlib", "functools", "itertools", "collections"], "answerIndex": 0, "explanation": "contextlib.contextmanager turns a generator function into a context manager." },
    { "id": "pya-q25", "prompt": "What is Method Resolution Order (MRO)?", "options": ["The order Python searches parent classes for a method", "The order methods are defined", "The order decorators are applied", "The order of argument evaluation"], "answerIndex": 0, "explanation": "Python's C3 linearisation algorithm determines which class's method is called in multiple inheritance." },
    { "id": "pya-q26", "prompt": "What does @property do?", "options": ["Lets you access a method like an attribute", "Makes an attribute read-only forever", "Caches the return value", "Deletes an attribute"], "answerIndex": 0, "explanation": "@property turns a method into a computed attribute — called with obj.name instead of obj.name()." },
    { "id": "pya-q27", "prompt": "What is the purpose of __slots__ in a class?", "options": ["Restricts instance attributes and saves memory", "Locks class from inheritance", "Speeds up method calls", "Enables pickling"], "answerIndex": 0, "explanation": "__slots__ replaces the per-instance __dict__ with a fixed-size array, reducing memory usage." },
    { "id": "pya-q28", "prompt": "What does filter(None, [0, 1, '', 'a', False, True]) return?", "options": ["[1, 'a', True]", "[0, '', False]", "[1, True]", "Everything"], "answerIndex": 0, "explanation": "filter(None, iterable) removes all falsy values." },
    { "id": "pya-q29", "prompt": "What is the output of (lambda x, y: x + y)(3, 4)?", "options": ["7", "34", "Error", "None"], "answerIndex": 0, "explanation": "The lambda is defined and immediately called with arguments 3 and 4." },
    { "id": "pya-q30", "prompt": "In multiple inheritance class C(A, B), which method wins if both A and B define foo()?", "options": ["A.foo() — leftmost parent wins", "B.foo()", "Both run", "A random one"], "answerIndex": 0, "explanation": "MRO searches left-to-right: C → A → B. A.foo() is found first." },
    { "id": "pya-q31", "prompt": "What does __enter__ return in a context manager?", "options": ["The object bound to the 'as' variable", "Always None", "A boolean success flag", "The exception if one occurred"], "answerIndex": 0, "explanation": "Whatever __enter__ returns is assigned to the variable after 'as' in the with statement." },
    { "id": "pya-q32", "prompt": "Which built-in function applies a function cumulatively to a sequence?", "options": ["reduce", "map", "filter", "accumulate"], "answerIndex": 0, "explanation": "functools.reduce(fn, seq) applies fn(acc, x) repeatedly to fold the sequence into one value." },
    { "id": "pya-q33", "prompt": "What does @wraps(func) do inside a decorator?", "options": ["Preserves the original function name and docstring", "Runs the original function first", "Makes the decorator stackable", "Speeds up the wrapper"], "answerIndex": 0, "explanation": "Without @wraps, the wrapper's __name__ and __doc__ overwrite the original function's metadata." },
    { "id": "pya-q34", "prompt": "What is the output of type(lambda: None).__name__?", "options": ["function", "lambda", "NoneType", "type"], "answerIndex": 0, "explanation": "Lambda functions are still of type 'function' — they are not a special type." },
    { "id": "pya-q35", "prompt": "What does asyncio.run(coro()) do?", "options": ["Creates an event loop, runs the coroutine, then closes the loop", "Runs the coroutine in a thread", "Schedules the coroutine for later", "Converts the coroutine to a regular function"], "answerIndex": 0, "explanation": "asyncio.run() is the standard entry point for async programs in Python 3.7+." },
    { "id": "pya-q36", "prompt": "What is a metaclass?", "options": ["A class whose instances are classes", "A class with no methods", "An abstract base class", "A class that cannot be instantiated"], "answerIndex": 0, "explanation": "A metaclass controls class creation. type is the default metaclass — every class is an instance of type." },
    { "id": "pya-q37", "prompt": "What does __getitem__(self, key) allow?", "options": ["obj[key] syntax on custom objects", "Iteration over the object", "Attribute access via dot notation", "Hashing of the object"], "answerIndex": 0, "explanation": "Implementing __getitem__ lets your class support indexing and slicing." },
    { "id": "pya-q38", "prompt": "What is the difference between an iterator and an iterable?", "options": ["An iterable can produce an iterator; an iterator has __next__", "They are the same thing", "An iterator is a type of list", "An iterable is faster"], "answerIndex": 0, "explanation": "An iterable implements __iter__. An iterator also implements __next__ and remembers its position." },
    { "id": "pya-q39", "prompt": "What does 'raise ValueError from original_error' do?", "options": ["Chains the new exception to the original", "Suppresses the original error", "Runs the original error handler again", "Re-raises the original error unchanged"], "answerIndex": 0, "explanation": "'raise X from Y' sets __cause__ on the new exception, creating an explicit exception chain." },
    { "id": "pya-q40", "prompt": "What is cooperative multitasking in asyncio?", "options": ["Tasks yield control voluntarily at await points", "Tasks run on separate CPU cores", "The OS switches tasks automatically", "Tasks run in random order"], "answerIndex": 0, "explanation": "asyncio is single-threaded. Tasks hand back control only when they hit an await — hence 'cooperative'." },
    { "id": "pya-q41", "prompt": "What does itertools.chain(*iterables) do?", "options": ["Iterates through multiple iterables as one", "Multiplies iterables together", "Zips iterables together", "Flattens nested lists"], "answerIndex": 0, "explanation": "chain() yields items from the first iterable, then the second, etc., without building a new list." },
    { "id": "pya-q42", "prompt": "What does __call__ allow you to do?", "options": ["Use an object like a function with obj()", "Iterate over an object", "Compare objects with ==", "Make a class abstract"], "answerIndex": 0, "explanation": "Implementing __call__ makes instances callable — obj() triggers obj.__call__()." },
    { "id": "pya-q43", "prompt": "What does @abstractmethod (from abc) enforce?", "options": ["Subclasses must implement the method or cannot be instantiated", "The method runs automatically", "The method is private", "The method cannot be overridden"], "answerIndex": 0, "explanation": "ABCs with @abstractmethod raise TypeError if a subclass does not implement them." },
    { "id": "pya-q44", "prompt": "What is the output of list(zip([1,2,3],[4,5]))?", "options": ["[(1,4),(2,5)]", "[(1,4),(2,5),(3,None)]", "Error", "[(1,4,3),(2,5)]"], "answerIndex": 0, "explanation": "zip stops at the shortest iterable. The 3 has no pair, so it is dropped." },
    { "id": "pya-q45", "prompt": "What does the walrus operator := do?", "options": ["Assigns a value and returns it in one expression", "Compares two values", "Divides and assigns", "Creates a generator"], "answerIndex": 0, "explanation": ":= (Python 3.8+) assigns inside an expression — useful in while loops and comprehension conditions." },
    { "id": "pya-q46", "prompt": "What is a dataclass (from dataclasses import dataclass)?", "options": ["A class that auto-generates __init__, __repr__, __eq__ from field annotations", "A class that stores only numbers", "A class that cannot have methods", "A subclass of dict"], "answerIndex": 0, "explanation": "@dataclass reads type annotations and auto-generates boilerplate methods." },
    { "id": "pya-q47", "prompt": "What does functools.lru_cache do?", "options": ["Memoizes function results for repeated calls", "Limits function calls per second", "Runs the function in parallel", "Logs every function call"], "answerIndex": 0, "explanation": "lru_cache stores results of previous calls. If called again with the same args, it returns the cached result instantly." },
    { "id": "pya-q48", "prompt": "What is the Global Interpreter Lock (GIL)?", "options": ["A mutex that allows only one thread to execute Python bytecode at a time", "A security feature that prevents imports", "A lock on global variables", "A tool for preventing race conditions in asyncio"], "answerIndex": 0, "explanation": "The GIL means Python threads cannot run bytecode truly in parallel. Use multiprocessing for CPU-bound parallelism." },
    { "id": "pya-q49", "prompt": "What does __hash__ need to be consistent with?", "options": ["__eq__ — objects that compare equal must have the same hash", "__repr__", "__str__", "__lt__"], "answerIndex": 0, "explanation": "If a == b then hash(a) must equal hash(b). Breaking this rule corrupts dict/set behaviour." },
    { "id": "pya-q50", "prompt": "What does async for do?", "options": ["Iterates over an async generator or async iterable", "Runs a for loop in parallel", "Creates an async list", "Replaces a regular for loop with a coroutine"], "answerIndex": 0, "explanation": "async for works with objects implementing __aiter__ and __anext__, allowing await inside each step." },

    { "id": "pya-q51", "prompt": "What happens if you define __eq__ without __hash__ in a class?", "options": ["__hash__ is set to None, making instances unhashable", "Python auto-generates __hash__", "The class raises TypeError at definition", "__hash__ is inherited from object"], "answerIndex": 0, "explanation": "Python automatically sets __hash__ = None when you define __eq__, making the object unhashable (cannot be used as a dict key or in a set)." },
    { "id": "pya-q52", "prompt": "What is the difference between threading and multiprocessing in Python?", "options": ["threading shares memory but is limited by the GIL; multiprocessing uses separate processes and bypasses the GIL", "They are identical", "multiprocessing uses threads", "threading is faster for CPU-bound tasks"], "answerIndex": 0, "explanation": "For CPU-bound tasks, use multiprocessing. For I/O-bound tasks, threading or asyncio are sufficient." },
    { "id": "pya-q53", "prompt": "What does __del__ do in Python?", "options": ["Called when the object is about to be garbage-collected", "Deletes a class attribute", "Removes an item from a list", "Raises an error"], "answerIndex": 0, "explanation": "__del__ is a finalizer. It is called when the reference count drops to zero. It is not guaranteed to run promptly." },
    { "id": "pya-q54", "prompt": "What does __contains__ enable?", "options": ["The 'in' operator on custom objects", "Iteration", "Comparison with ==", "Hashing"], "answerIndex": 0, "explanation": "Implementing __contains__(self, item) lets you write 'item in my_obj'." },
    { "id": "pya-q55", "prompt": "What is the output of next(iter([]))?", "options": ["StopIteration raised", "None", "[]", "0"], "answerIndex": 0, "explanation": "iter([]) creates an empty iterator. Calling next() on it immediately raises StopIteration." },
    { "id": "pya-q56", "prompt": "What does TypeVar do in Python's typing module?", "options": ["Declares a generic type placeholder for type hints", "Creates a new type at runtime", "Validates a variable's type", "Converts between types"], "answerIndex": 0, "explanation": "TypeVar is used with generics (e.g. List[T]) to write type-safe reusable functions and classes." },
    { "id": "pya-q57", "prompt": "What does @dataclass(frozen=True) do?", "options": ["Makes the dataclass immutable — attributes cannot be reassigned after creation", "Prevents the class from being subclassed", "Freezes the Python interpreter", "Makes all fields optional"], "answerIndex": 0, "explanation": "frozen=True generates __hash__ and raises FrozenInstanceError on attempted attribute modification." },
    { "id": "pya-q58", "prompt": "What does collections.defaultdict do differently from a regular dict?", "options": ["Automatically creates a default value for missing keys", "Raises a custom error on missing keys", "Sorts keys automatically", "Is faster than a regular dict"], "answerIndex": 0, "explanation": "defaultdict(list) means accessing a missing key automatically inserts an empty list instead of raising KeyError." },
    { "id": "pya-q59", "prompt": "What does inspect.signature(fn) return?", "options": ["The function's parameter signature", "The function's source code", "The function's return type", "The function's call count"], "answerIndex": 0, "explanation": "inspect.signature gives a Signature object describing the function's parameters, useful for introspection and decorators." },
    { "id": "pya-q60", "prompt": "What is the purpose of __class_getitem__ (e.g. list[int])?", "options": ["Enables generic subscript syntax like list[int] without a metaclass", "Creates a new class", "Checks if an item is in the class", "Overrides __getitem__ for all instances"], "answerIndex": 0, "explanation": "__class_getitem__ is called when you write SomeClass[T], enabling PEP 585 generics like list[int]." },
    { "id": "pya-q61", "prompt": "What does sys.exit(0) do?", "options": ["Exits the program with a success code", "Raises a RuntimeError", "Restarts the interpreter", "Returns 0 from main()"], "answerIndex": 0, "explanation": "sys.exit() raises SystemExit. By convention, 0 = success, non-zero = error." },
    { "id": "pya-q62", "prompt": "What is the output of bool(b'') (empty bytes)?", "options": ["False", "True", "TypeError", "b'False'"], "answerIndex": 0, "explanation": "Empty bytes objects are falsy, just like empty strings and empty lists." },
    { "id": "pya-q63", "prompt": "What does itertools.islice(gen, 5) do?", "options": ["Returns the first 5 items of an iterable without consuming the rest", "Slices a list", "Creates a new generator of 5 items", "Raises an error on generators"], "answerIndex": 0, "explanation": "islice works on any iterable (including infinite generators) and stops after the given count." },
    { "id": "pya-q64", "prompt": "In Python, what does 'raise' with no argument do inside an except block?", "options": ["Re-raises the currently active exception", "Raises a new RuntimeError", "Exits the program", "Does nothing"], "answerIndex": 0, "explanation": "A bare 'raise' re-raises the exception currently being handled, preserving the original traceback." },
    { "id": "pya-q65", "prompt": "What does __init_subclass__ allow a parent class to do?", "options": ["Run code whenever a subclass is defined", "Override __init__ in all subclasses", "Prevent all subclassing", "Automatically call super().__init__()"], "answerIndex": 0, "explanation": "__init_subclass__ is called on the parent class each time it is subclassed, useful for plugin systems." },
    { "id": "pya-q66", "prompt": "What does collections.Counter({'a': 3, 'b': 1}).most_common(1) return?", "options": ["[('a', 3)]", "[('b', 1)]", "{'a': 3}", "3"], "answerIndex": 0, "explanation": "most_common(n) returns the n most frequent elements as a list of (element, count) tuples." },
    { "id": "pya-q67", "prompt": "What is the difference between a coroutine and a thread?", "options": ["Coroutines are cooperative and single-threaded; threads are preemptive and OS-scheduled", "They are identical", "Threads use less memory", "Coroutines run on multiple CPUs"], "answerIndex": 0, "explanation": "Coroutines yield control explicitly at 'await'; threads are interrupted by the OS scheduler." },
    { "id": "pya-q68", "prompt": "What does __set_name__(self, owner, name) do in a descriptor?", "options": ["Called when the descriptor is assigned to a class attribute, passing the class and attribute name", "Called when an attribute is set on an instance", "Sets a default value for the descriptor", "Renames the descriptor"], "answerIndex": 0, "explanation": "__set_name__ lets a descriptor know which attribute name it was assigned to, enabling self-referential descriptors." },
    { "id": "pya-q69", "prompt": "What does importlib.import_module('os.path') do?", "options": ["Dynamically imports a module by name string", "Reloads a previously imported module", "Lists available modules", "Installs a module"], "answerIndex": 0, "explanation": "importlib.import_module allows importing modules programmatically using a string name." },
    { "id": "pya-q70", "prompt": "What is the purpose of __all__ in a Python module?", "options": ["Defines the public API exported when 'from module import *' is used", "Imports all symbols automatically", "Lists all functions in the module", "Restricts all imports"], "answerIndex": 0, "explanation": "__all__ is a list of names. Only those names are exported by 'from module import *'; it also documents the public interface." },
    { "id": "pya-q71", "prompt": "What does functools.cache differ from lru_cache?", "options": ["cache has no max size limit; lru_cache evicts old entries when the limit is reached", "They are identical", "cache is faster", "lru_cache is unbounded"], "answerIndex": 0, "explanation": "@cache (Python 3.9+) is equivalent to @lru_cache(maxsize=None) — it never evicts cached results." },
    { "id": "pya-q72", "prompt": "What does a class decorated with @runtime_checkable (from typing) allow?", "options": ["isinstance() checks against a Protocol", "Faster method dispatch", "Automatic method generation", "Type checking at compile time"], "answerIndex": 0, "explanation": "Without @runtime_checkable, Protocol classes cannot be used in isinstance() checks at runtime." },
    { "id": "pya-q73", "prompt": "What does 'except* ValueError' (Python 3.11+) do?", "options": ["Handles ValueError exceptions inside an ExceptionGroup", "Catches all subclasses of ValueError", "Suppresses ValueError", "Is equivalent to 'except ValueError'"], "answerIndex": 0, "explanation": "'except*' is used with ExceptionGroups (PEP 654), allowing structured concurrency to surface multiple exceptions at once." },
    { "id": "pya-q74", "prompt": "What does __post_init__ do in a dataclass?", "options": ["Runs after the auto-generated __init__, useful for validation or derived fields", "Replaces __init__", "Runs before field assignment", "Is called when the object is deleted"], "answerIndex": 0, "explanation": "@dataclass calls __post_init__() at the end of __init__(), letting you add custom initialisation logic." },
    { "id": "pya-q75", "prompt": "What is the output of type('Dog', (object,), {'speak': lambda self: 'Woof'})().speak()?", "options": ["Woof", "Error", "'Woof'", "None"], "answerIndex": 0, "explanation": "type(name, bases, dict) is the functional form of class creation. It returns a new class, and () creates an instance." }
  ],
  "practice": [
    { "id": "pya-p1", "title": "Simple Class", "prompt": "Create a Neuron class with forward(x) that computes weight*x + bias.", "starterCode": "class Neuron:\n    def __init__(self, weight, bias):\n        self.weight = weight\n        self.bias = bias\n    def forward(self, x):\n        return self.weight * x + self.bias\n\nn = Neuron(0.5, 2)\nprint(n.forward(10))", "expectedOutput": "7.0", "hint": "forward returns self.weight * x + self.bias." },
    { "id": "pya-p2", "title": "Generator Range", "prompt": "Write a generator that yields squares from 0 to n-1.", "starterCode": "def squares_gen(n):\n    for i in range(n):\n        yield i ** 2\n\nprint(list(squares_gen(5)))", "expectedOutput": "[0, 1, 4, 9, 16]", "hint": "Use yield inside a for loop." },
    { "id": "pya-p3", "title": "Safe Division", "prompt": "Write a function that handles ZeroDivisionError.", "starterCode": "def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return \"Error\"\n\nprint(safe_divide(10, 0))", "expectedOutput": "Error", "hint": "Wrap the division in try/except ZeroDivisionError." },
    { "id": "pya-p4", "title": "Inheritance", "prompt": "Create Animal and Dog classes where Dog overrides speak().", "starterCode": "class Animal:\n    def speak(self):\n        return \"...\"\n\nclass Dog(Animal):\n    def speak(self):\n        return \"Woof!\"\n\nprint(Dog().speak())", "expectedOutput": "Woof!", "hint": "Override the speak method in the Dog class." },
    { "id": "pya-p5", "title": "Math Module", "prompt": "Use the math module to compute the square root of 144.", "starterCode": "import math\nprint(math.sqrt(144))", "expectedOutput": "12.0", "hint": "math.sqrt() returns the square root as a float." },
    { "id": "pya-p6", "title": "Counter Decorator", "prompt": "Write a decorator count_calls that prints how many times a function has been called.", "starterCode": "from functools import wraps\n\ndef count_calls(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        wrapper.calls += 1\n        print(f\"Call #{wrapper.calls}\")\n        return func(*args, **kwargs)\n    wrapper.calls = 0\n    return wrapper\n\n@count_calls\ndef greet(name):\n    print(f\"Hello, {name}!\")\n\ngreet(\"Ada\")\ngreet(\"Turing\")", "expectedOutput": "Call #1\nHello, Ada!\nCall #2\nHello, Turing!", "hint": "Store a 'calls' counter on the wrapper function object itself." },
    { "id": "pya-p7", "title": "Fibonacci Generator", "prompt": "Write an infinite Fibonacci generator and print the first 8 values.", "starterCode": "def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\nfib = fibonacci()\nprint([next(fib) for _ in range(8)])", "expectedOutput": "[0, 1, 1, 2, 3, 5, 8, 13]", "hint": "An infinite generator never raises StopIteration — use next() to pull values." },
    { "id": "pya-p8", "title": "Dunder __repr__", "prompt": "Add __repr__ to a Vector class so repr(Vector(3,4)) shows 'Vector(3, 4)'.", "starterCode": "class Vector:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n    def __repr__(self):\n        return f\"Vector({self.x}, {self.y})\"\n\nprint(repr(Vector(3, 4)))", "expectedOutput": "Vector(3, 4)", "hint": "__repr__ should return a string that looks like the constructor call." },
    { "id": "pya-p9", "title": "Custom Exception", "prompt": "Define a ValidationError and raise it when a value is negative.", "starterCode": "class ValidationError(Exception):\n    pass\n\ndef check_positive(n):\n    if n < 0:\n        raise ValidationError(f\"{n} is not positive\")\n    return n\n\ntry:\n    check_positive(-5)\nexcept ValidationError as e:\n    print(e)", "expectedOutput": "-5 is not positive", "hint": "Subclass Exception and pass a message to super().__init__()." },
    { "id": "pya-p10", "title": "Dict Comprehension", "prompt": "Create a dict mapping numbers 1-5 to their cubes.", "starterCode": "cubes = {x: x**3 for x in range(1, 6)}\nprint(cubes)", "expectedOutput": "{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}", "hint": "{key: value for var in iterable}." },
    { "id": "pya-p11", "title": "Context Manager", "prompt": "Write a context manager using @contextmanager that prints 'start' and 'end' around a block.", "starterCode": "from contextlib import contextmanager\n\n@contextmanager\ndef bookend(label):\n    print(f\"start: {label}\")\n    yield\n    print(f\"end: {label}\")\n\nwith bookend(\"task\"):\n    print(\"working...\")", "expectedOutput": "start: task\nworking...\nend: task", "hint": "Everything before yield runs on entry, everything after runs on exit." },
    { "id": "pya-p12", "title": "Partial Functions", "prompt": "Use functools.partial to create a double() function from multiply(a, b).", "starterCode": "from functools import partial\n\ndef multiply(a, b):\n    return a * b\n\ndouble = partial(multiply, b=2)\nprint(double(5))\nprint(double(21))", "expectedOutput": "10\n42", "hint": "partial(fn, b=2) pre-fills b — only a is needed when calling double()." },
    { "id": "pya-p13", "title": "Property Decorator", "prompt": "Add a @property 'area' to a Rectangle class that computes width * height without being called as a method.", "starterCode": "class Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n\n    @property\n    def area(self):\n        return self.width * self.height\n\nr = Rectangle(4, 5)\nprint(r.area)", "expectedOutput": "20", "hint": "@property lets you access area as r.area, not r.area()." },
    { "id": "pya-p14", "title": "Dunder __add__", "prompt": "Implement __add__ on a Vector class so v1 + v2 returns a new Vector with summed components.", "starterCode": "class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n    def __repr__(self):\n        return f\"Vector({self.x}, {self.y})\"\n\nprint(Vector(1, 2) + Vector(3, 4))", "expectedOutput": "Vector(4, 6)", "hint": "__add__ receives self and other, and should return a new Vector." },
    { "id": "pya-p15", "title": "LRU Cache", "prompt": "Use @lru_cache to memoize a recursive Fibonacci function and print fib(10).", "starterCode": "from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n-1) + fib(n-2)\n\nprint(fib(10))", "expectedOutput": "55", "hint": "@lru_cache stores results so fib(n) is only computed once per unique n." },
    { "id": "pya-p16", "title": "Async Concurrent Fetch", "prompt": "Use asyncio.gather to run two coroutines concurrently and collect their results.", "starterCode": "import asyncio\n\nasync def fetch(name, delay):\n    await asyncio.sleep(delay)\n    return f\"done: {name}\"\n\nasync def main():\n    results = await asyncio.gather(fetch(\"A\", 1), fetch(\"B\", 1))\n    for r in results:\n        print(r)\n\nasyncio.run(main())", "expectedOutput": "done: A\ndone: B", "hint": "gather runs coroutines concurrently, so both finish in ~1s total, not 2s." },
    { "id": "pya-p17", "title": "Iterator Class", "prompt": "Write a Countdown iterator class that counts down from n to 1.", "starterCode": "class Countdown:\n    def __init__(self, n):\n        self.n = n\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.n <= 0:\n            raise StopIteration\n        val = self.n\n        self.n -= 1\n        return val\n\nprint(list(Countdown(5)))", "expectedOutput": "[5, 4, 3, 2, 1]", "hint": "Raise StopIteration when there are no more values." },
    { "id": "pya-p18", "title": "Exception Chaining", "prompt": "Catch a ValueError and raise a RuntimeError with 'from e' to chain the exceptions.", "starterCode": "def parse_config(value):\n    try:\n        return int(value)\n    except ValueError as e:\n        raise RuntimeError(f\"Config error: bad value {value!r}\") from e\n\ntry:\n    parse_config(\"bad\")\nexcept RuntimeError as e:\n    print(e)", "expectedOutput": "Config error: bad value 'bad'", "hint": "'raise X from Y' chains exceptions. The original is stored in e.__cause__." },
    { "id": "pya-p19", "title": "yield from", "prompt": "Write a chain_gen(*iters) generator using yield from that iterates through all provided iterables.", "starterCode": "def chain_gen(*iterables):\n    for it in iterables:\n        yield from it\n\nprint(list(chain_gen([1,2], \"ab\", (3,4))))", "expectedOutput": "[1, 2, 'a', 'b', 3, 4]", "hint": "'yield from iterable' delegates all values from that iterable." },
    { "id": "pya-p20", "title": "Dataclass", "prompt": "Use @dataclass to create a Point class with x and y fields, then print a Point instance.", "starterCode": "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: float\n    y: float\n\np = Point(3.0, 4.0)\nprint(p)", "expectedOutput": "Point(x=3.0, y=4.0)", "hint": "@dataclass auto-generates __init__ and __repr__ from the annotated fields." },
    {
      "id": "pya-p21", "title": "Abstract Base Class", "prompt": "Use ABC and @abstractmethod to enforce that all subclasses implement an area() method.",
      "starterCode": "from abc import ABC, abstractmethod\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\nclass Circle(Shape):\n    def __init__(self, r):\n        self.r = r\n    def area(self):\n        import math\n        return round(math.pi * self.r ** 2, 2)\n\nprint(Circle(5).area())",
      "expectedOutput": "78.54",
      "hint": "Subclasses that don't implement all abstractmethods will raise TypeError on instantiation."
    },
    {
      "id": "pya-p22", "title": "defaultdict", "prompt": "Use collections.defaultdict to group words by their first letter.",
      "starterCode": "from collections import defaultdict\n\nwords = ['apple', 'ant', 'banana', 'avocado', 'blueberry']\ngrouped = defaultdict(list)\nfor w in words:\n    grouped[w[0]].append(w)\nprint(dict(sorted(grouped.items())))",
      "expectedOutput": "{'a': ['apple', 'ant', 'avocado'], 'b': ['banana', 'blueberry']}",
      "hint": "defaultdict(list) auto-creates an empty list for any new key."
    },
    {
      "id": "pya-p23", "title": "Descriptor Protocol", "prompt": "Write a TypedAttribute descriptor that raises TypeError if the value assigned is not an int.",
      "starterCode": "class TypedInt:\n    def __set_name__(self, owner, name):\n        self.name = name\n    def __get__(self, obj, objtype=None):\n        return getattr(obj, f'_{self.name}', None)\n    def __set__(self, obj, value):\n        if not isinstance(value, int):\n            raise TypeError(f'{self.name} must be int')\n        setattr(obj, f'_{self.name}', value)\n\nclass Person:\n    age = TypedInt()\n\np = Person()\np.age = 30\nprint(p.age)\ntry:\n    p.age = 'old'\nexcept TypeError as e:\n    print(e)",
      "expectedOutput": "30\nage must be int",
      "hint": "__set_name__ is called automatically when the descriptor is assigned to a class body."
    },
    {
      "id": "pya-p24", "title": "Singleton Metaclass", "prompt": "Implement a Singleton metaclass so that only one instance of a class can ever exist.",
      "starterCode": "class Singleton(type):\n    _instances = {}\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass Config(metaclass=Singleton):\n    pass\n\na = Config()\nb = Config()\nprint(a is b)",
      "expectedOutput": "True",
      "hint": "Override __call__ in the metaclass to intercept instance creation."
    },
    {
      "id": "pya-p25", "title": "Async Context Manager", "prompt": "Write an async context manager class using __aenter__ and __aexit__ that prints 'open' and 'close'.",
      "starterCode": "import asyncio\n\nclass AsyncResource:\n    async def __aenter__(self):\n        print('open')\n        return self\n    async def __aexit__(self, *args):\n        print('close')\n\nasync def main():\n    async with AsyncResource():\n        print('using')\n\nasyncio.run(main())",
      "expectedOutput": "open\nusing\nclose",
      "hint": "async with calls __aenter__ on entry and __aexit__ on exit, both of which can use await."
    }
  ],
};
